/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HomeOffice2_v2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { gsap } from 'gsap'
import { useNavigate } from 'react-router'

export default function Model(props) {
  let navigate = useNavigate()
  const { nodes, materials } = useGLTF('/models/HomeOffice2_v2.glb')
  const whiteMaterial = new THREE.MeshBasicMaterial({ color: 0xffffff})

  const aboutAnimRef = useRef()
  const devWorkAnimRef = useRef()

  const animationPairs = {
    About_Hitbox: { ref: aboutAnimRef },
    Dev_Work_Hitbox: { ref: devWorkAnimRef },
    
  }
  const originalScales = {
    About_Hitbox: { x: 0.009, y: 0.009, z: 0.011 },
    Dev_Work_Hitbox: { x: 0.018, y: 0.018, z: 0.021 }
  };
  // Handle Hover
  const onHover = (key, isHovering) => {
    const animObject = animationPairs[key]
  // Như này to quá
  //   gsap.to(animObject.ref.current.scale, {
  //     x: isHovering ? 1 : 0,
  //     y: isHovering ? 1 : 0,
  //     z: isHovering ? 1 : 0, 
  //     duration: 0.8,
  // })
    const base = originalScales[key];
    gsap.to(animObject.ref.current.scale, {
      x: isHovering ? base.x  : 0,
      y: isHovering ? base.y : 0,
      z: isHovering ? base.z : 0,
      duration: 0.9,
      ease: "power1.out"
    });
  }
  return (
    <group {...props} dispose={null}>
      <group position={[-1.831, 1.669, 1.015]} rotation={[1.58, 0.011, -1.493]} scale={[2.112, 1.827, 1.825]}>
        <group position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cube012_1.geometry} material={materials['Material.009']} />
          <mesh geometry={nodes.Cube012_2.geometry} material={materials['paper.001']} />
        </group>
        <group position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cube013_1.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Cube013_2.geometry} material={materials['paper.001']} />
        </group>
        <mesh geometry={nodes.Cube010.geometry} material={materials['Ground.001']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Cube011.geometry} material={materials['Ceramica off white.002']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Cylinder.geometry} material={materials['Vidro colorido.002']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
        <group position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh026.geometry} material={materials['Candle Wax.001']} />
          <mesh geometry={nodes.Mesh026_1.geometry} material={materials['Rope.001']} />
        </group>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Vidro.002']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
        <group position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh028.geometry} material={materials['Wood.003']} />
          <mesh geometry={nodes.Mesh028_1.geometry} material={materials['Material.011']} />
        </group>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials['Vidro colorido.002']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Plane025.geometry} material={materials['Material.012']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.shelf.geometry} material={materials['laqueado brilhoso branco.001']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0.132, 0.092, -1.54]} scale={[1.045, 1.045, 1.21]}>
        <mesh geometry={nodes.Buttons.geometry} material={materials['Material.013']} position={[0, -0.001, 0]} />
        <mesh geometry={nodes.Sofa_frame.geometry} material={materials['Material.014']} position={[0.018, -0.12, 0.032]} />
      </group>
      <group position={[0.361, 0.128, 0.751]} rotation={[0, -1.551, 0]} scale={[1.243, 1.074, 1.074]}>
        <mesh geometry={nodes.Desk_Side.geometry} material={materials['Wood Parquet.001']} />
        <mesh geometry={nodes.Desk_Spacer.geometry} material={materials['Wood Parquet.001']} />
        <mesh geometry={nodes.Desk_Top.geometry} material={materials['Wood dark.001']} />
        <mesh geometry={nodes.Drawer_Bottom.geometry} material={materials['White Wood.001']} />
        <mesh geometry={nodes.Drawer_Top.geometry} material={materials['Wood Parquet.001']} />
        <mesh geometry={nodes.Drawers_Back.geometry} material={materials['Wood Parquet.001']} />
        <mesh geometry={nodes.Drawers_Sides.geometry} material={materials['Wood dark.001']} />
        <mesh geometry={nodes.Drawers_Spacer.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Drawers_Top.geometry} material={materials['Wood Parquet.001']} />
      </group>
      <group position={[0.361, 0.128, 0.751]} rotation={[0, -1.551, 0]} scale={[1.243, 1.074, 1.074]}>
        <mesh geometry={nodes.Desk_Side001.geometry} material={materials['Wood Parquet.001']} />
        <mesh geometry={nodes.Desk_Spacer001.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Desk_Top001.geometry} material={materials['Wood.004']} />
        <mesh geometry={nodes.Drawer_Bottom001.geometry} material={materials['White Wood.002']} />
        <mesh geometry={nodes.Drawer_Top001.geometry} material={materials['White Wood.002']} />
        <mesh geometry={nodes.Drawers_Back001.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Drawers_Sides001.geometry} material={materials['Wood.004']} />
        <mesh geometry={nodes.Drawers_Spacer001.geometry} material={materials['White Wood.002']} />
        <mesh geometry={nodes.Drawers_Top001.geometry} material={materials['Wood.004']} />
      </group>
      <group position={[0.72, 1.021, 0.813]} rotation={[0, -0.276, 0]} scale={[1.268, 1.252, 1.436]}>
        <group position={[-0.001, -0.058, -0.341]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Plane005_1.geometry} material={materials['Cover book-01.001']} />
          <mesh geometry={nodes.Plane005_2.geometry} material={materials['paper.002']} />
        </group>
        <group position={[-0.001, -0.058, -0.341]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Plane006_1.geometry} material={materials['Cover book-02.001']} />
          <mesh geometry={nodes.Plane006_2.geometry} material={materials['paper.002']} />
        </group>
        <group position={[-0.001, -0.058, -0.341]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Plane007.geometry} material={materials['Cover book-03.001']} />
          <mesh geometry={nodes.Plane007_1.geometry} material={materials['paper.002']} />
        </group>
      </group>
      <group position={[0.896, 0.956, 1.121]} scale={[1.33, 1.33, 1.54]}>
        <mesh geometry={nodes.Black_metal001.geometry} material={materials['Black metal.001']} />
        <mesh geometry={nodes.Bulb001.geometry} material={materials['Glass.001']} />
        <mesh geometry={nodes.Fabric001.geometry} material={materials['Fabric.001']} />
        <mesh geometry={nodes.Rattan001.geometry} material={materials['Rattan.001']} />
        <mesh geometry={nodes.White_metal001.geometry} material={materials['White metal.001']} />
      </group>
      <group position={[0.048, 0.771, 1.116]} scale={[0.158, 0.158, 0.183]}>
        <group scale={6.182}>
          <mesh geometry={nodes.Circle001.geometry} material={materials['Plant_Pot.001']} />
          <mesh geometry={nodes.Circle001_1.geometry} material={materials['Plant_Soil.001']} />
        </group>
        <mesh geometry={nodes.IVY_Curve004.geometry} material={materials['Plant_Stem.001']} scale={6.182} />
        <mesh geometry={nodes.Plane005.geometry} material={materials['Plant_Leaf.001']} scale={6.182} />
      </group>
      <group position={[0.606, 0.441, 1.231]} rotation={[0, -1.408, 0]} scale={[1.659, 1.437, 1.443]}>
        <group position={[-0.727, -0.997, 0.413]}>
          <mesh geometry={nodes.Cube046.geometry} material={materials['Material.021']} />
          <mesh geometry={nodes.Cube046_1.geometry} material={materials['paper.003']} />
        </group>
        <group position={[-0.727, -0.997, 0.413]}>
          <mesh geometry={nodes.Cube047.geometry} material={materials['Material.022']} />
          <mesh geometry={nodes.Cube047_1.geometry} material={materials['paper.003']} />
        </group>
        <group position={[-0.727, -0.997, 0.413]}>
          <mesh geometry={nodes.Cube048.geometry} material={materials['Material.023']} />
          <mesh geometry={nodes.Cube048_1.geometry} material={materials['paper.003']} />
        </group>
        <group position={[-0.727, -0.997, 0.413]}>
          <mesh geometry={nodes.Cube049.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube049_1.geometry} material={materials['paper.003']} />
        </group>
        <group position={[-0.727, -0.997, 0.413]}>
          <mesh geometry={nodes.Cube050.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Cube050_1.geometry} material={materials['paper.003']} />
        </group>
        <group position={[-0.727, -0.997, 0.413]}>
          <mesh geometry={nodes.Cube051.geometry} material={materials['Material.026']} />
          <mesh geometry={nodes.Cube051_1.geometry} material={materials['paper.003']} />
        </group>
        <group position={[-0.727, -0.997, 0.413]}>
          <mesh geometry={nodes.Cube052.geometry} material={materials['Material.027']} />
          <mesh geometry={nodes.Cube052_1.geometry} material={materials['paper.003']} />
        </group>
      </group>
      <group position={[0.561, 0.145, 1.228]} rotation={[0, -1.552, 0]} scale={[0.9, 0.778, 0.778]}>
        <group position={[0, 0.127, 0.118]}>
          <mesh geometry={nodes.Cube053.geometry} material={materials['1984.001']} />
          <mesh geometry={nodes.Cube053_1.geometry} material={materials['edge paper.001']} />
        </group>
        <group position={[0, 0.127, 0.118]}>
          <mesh geometry={nodes.Cube054.geometry} material={materials['design.001']} />
          <mesh geometry={nodes.Cube054_1.geometry} material={materials['edge paper.002']} />
        </group>
        <group position={[0, 0.127, 0.118]}>
          <mesh geometry={nodes.Cube055.geometry} material={materials['factful.001']} />
          <mesh geometry={nodes.Cube055_1.geometry} material={materials['edge paper.002']} />
          <mesh geometry={nodes.Cube055_2.geometry} material={materials['factful.002']} />
        </group>
        <group position={[0, 0.127, 0.118]}>
          <mesh geometry={nodes.Cube056.geometry} material={materials['greenbook.001']} />
          <mesh geometry={nodes.Cube056_1.geometry} material={materials['edge paper.003']} />
        </group>
        <group position={[0, 0.127, 0.118]}>
          <mesh geometry={nodes.Cube057.geometry} material={materials['how to.001']} />
          <mesh geometry={nodes.Cube057_1.geometry} material={materials['edge paper.002']} />
        </group>
        <group position={[0, 0.127, 0.118]}>
          <mesh geometry={nodes.Cube058.geometry} material={materials['hygge.001']} />
          <mesh geometry={nodes.Cube058_1.geometry} material={materials['edge paper.004']} />
        </group>
        <group position={[0, 0.127, 0.118]}>
          <mesh geometry={nodes.Cube059.geometry} material={materials['ikigai.001']} />
          <mesh geometry={nodes.Cube059_1.geometry} material={materials['edge paper.005']} />
        </group>
        <group position={[0, 0.127, 0.118]}>
          <mesh geometry={nodes.Cube060.geometry} material={materials['subtle.001']} />
          <mesh geometry={nodes.Cube060_1.geometry} material={materials['edge paper.001']} />
        </group>
        <group position={[0, 0.127, 0.118]}>
          <mesh geometry={nodes.Cube061.geometry} material={materials['sapiens.001']} />
          <mesh geometry={nodes.Cube061_1.geometry} material={materials['edge paper.002']} />
        </group>
      </group>
      <group position={[-1.674, 0.07, 0.461]} scale={[1.078, 1.078, 1.249]}>
        <mesh geometry={nodes.ground001.geometry} material={materials['TT_checker_1024x1024_UV_GRID.003']} />
        <mesh geometry={nodes.plant001.geometry} material={materials['leave_1_MatSG.001']} />
        <mesh geometry={nodes.pot001.geometry} material={materials['Material.028']} />
      </group>
      <group position={[0.264, 1.365, -2.036]} rotation={[1.595, -0.003, 0.008]} scale={[1.006, 1.165, 1.006]}>
        <mesh geometry={nodes.Glass.geometry} material={materials['Glass.002']} position={[0, -0.085, -0.612]} />
      </group>
      <group position={[0.069, 0.999, -2.056]} scale={[1.45, 1.45, 1.679]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['glass.001']}>
          <group position={[0.485, 0, 0]}>
            <mesh geometry={nodes.Cube064.geometry} material={materials['Material.029']} />
            <mesh geometry={nodes.Cube064_1.geometry} material={materials['black rubber.001']} />
          </group>
        </mesh>
        <mesh geometry={nodes.Cube005.geometry} material={materials['White Vinyl.001']}>
          <mesh geometry={nodes.Cube009.geometry} material={materials['black rubber.001']} position={[-0.053, -0.89, 1.21]} scale={1.259} />
        </mesh>
        <mesh geometry={nodes.Cube062.geometry} material={materials['glass.001']} />
        <mesh geometry={nodes.Cube062_1.geometry} material={materials['White Vinyl.001']} />
        <mesh geometry={nodes.Cube062_2.geometry} material={materials['black rubber.001']} />
      </group>
      <pointLight intensity={15} decay={2.5} distance={15} color="#fffaa2" position={[-0.01, 2.847, -0.054]} rotation={[-Math.PI / 2, 0, 0]} scale={[-13.97, -16.179, -34.387]} />
      <pointLight intensity={20} decay={2.5} distance={15} color="#fffaa2" position={[-0.01, 4.647, -0.054]} rotation={[-Math.PI / 2, 0, 0]} scale={[-13.97, -16.179, -34.387]} />      
      <mesh geometry={nodes.Plane.geometry} material={materials['Wooden Floor.001']} position={[-0.007, 0.004, -0.024]} scale={[1.825, 0.637, 2.113]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.007']} position={[-0.007, -0.003, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes.bookshelf002.geometry} material={materials['Material.008']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes.bookshelf.geometry} material={materials['Wood.002']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes['books-3981515_0001_Layer-3004'].geometry} material={materials['books-3981515_0001_Layer-3.002']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes['books-3981515_0001_Layer-3003'].geometry} material={materials['books-3981515_0001_Layer-3.002']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes['books-3981515_0001_Layer-3002'].geometry} material={materials['books-3981515_0001_Layer-3.002']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes['books-3981515_0001_Layer-3'].geometry} material={materials['books-3981515_0001_Layer-3.002']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes['books-3981515_0000_Layer-2005'].geometry} material={materials['books-3981515_0000_Layer-2.001']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes['books-3981515_0000_Layer-2004'].geometry} material={materials['books-3981515_0000_Layer-2.001']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes['books-3981515_0000_Layer-2003'].geometry} material={materials['books-3981515_0000_Layer-2.001']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes['books-3981515_0000_Layer-2002'].geometry} material={materials['books-3981515_0000_Layer-2.001']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes.polstar_2.geometry} material={materials['Material.015']} position={[-0.01, -0.447, 0.078]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes.polstar_2001.geometry} material={materials['Material.016']} position={[-0.005, -0.433, 0.05]} scale={[1.825, 1.825, 2.113]} />
      <mesh geometry={nodes.Beige_Carpet001.geometry} material={materials['Material.018']} position={[0.013, -0.286, -0.068]} scale={[1.825, 1.825, 2.113]} />
      <group position={[-0.027, 0.099, 0.086]} rotation={[0, 0.862, 0]} scale={[1.125, 1.029, 1.101]}>
        <mesh geometry={nodes.Plane010.geometry} material={materials['Office Chair_Fabric.001']} />
        <mesh geometry={nodes.Plane010_1.geometry} material={materials['Office Chair_Metal.001']} />
        <mesh geometry={nodes.Plane010_2.geometry} material={materials['Office Chair_Painted Metal.001']} />
        <mesh geometry={nodes.Plane010_3.geometry} material={materials['Office Chair_Plastic.001']} />
      </group>
      <mesh geometry={nodes.Lenovo_laptop.geometry} material={materials['prop_laptop_lenovo_body.001']} position={[0.79, 0.949, -0.045]} rotation={[0, -0.876, 0]} scale={0.001} />
      <group position={[-1.809, 1.973, -0.004]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.032, -0.891, -0.891]}>
        <mesh geometry={nodes.Plane011.geometry} material={materials['Picture_1.001']} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials['Frame_Black.001']} />
      </group>
      <mesh geometry={nodes.Plane006.geometry} material={materials.Material} position={[-0.599, 0, 0]} rotation={[-Math.PI, 0, 0]} scale={[2, 7.85, 2]} />
      <mesh
        geometry={nodes.About_Hitbox.geometry}
        material={nodes.About_Hitbox.material}
        visible={false}
        position={[-1.737, 1.952, 0.013]}
        scale={[0.073, 0.438, 0.613]}
        onPointerOver={() => {
          onHover("About_Hitbox", true)
          document.body.style.cursor = "pointer"
        }}
        onPointerOut={() => {
          onHover("About_Hitbox", false)
          document.body.style.cursor = "auto"
        }}
        onClick={() => {
          // openPanel("About_Hitbox")
          navigate("/about")
        }}
      />
      <mesh
        ref={aboutAnimRef}
        geometry={nodes.About_Hitbox_Anim.geometry}
        material={whiteMaterial}
        position={[-1.664, 2.39, 0.626]}
        scale={[0.009, 0.009, 0.011]}
      />
      <mesh
        geometry={nodes.Dev_Work_Hitbox.geometry}
        material={nodes.Dev_Work_Hitbox.material}
        visible={false}
        position={[0.391, 0.82, 0.497]}
        scale={[0.748, 0.693, 0.951]}
        onPointerOver={() => {
          onHover("Dev_Work_Hitbox", true)
          document.body.style.cursor = "pointer"
        }}
        onPointerOut={() => {
          onHover("Dev_Work_Hitbox", false)
          document.body.style.cursor = "auto"
        }}
        onClick={() => {
          // openPanel("Dev_Work_Hitbox")
          navigate("/dev-work")
        }}
      />
      <mesh
        ref={devWorkAnimRef}
        geometry={nodes.Dev_Work_Hitbox_Anim.geometry}
        material={whiteMaterial}
        position={[1.126, 1.5, 1.432]}
        scale={[0.018, 0.018, 0.021]}
      />
      {/* <mesh geometry={nodes.Dev_Work_Hitbox.geometry} material={nodes.Dev_Work_Hitbox.material} position={[0.391, 0.82, 0.497]} scale={[0.748, 0.693, 0.951]} />
      <mesh geometry={nodes.Dev_Work_Hitbox_Anim.geometry} material={nodes.Dev_Work_Hitbox_Anim.material} position={[1.126, 1.5, 1.432]} scale={[0.018, 0.018, 0.021]} />
      <mesh geometry={nodes.About_Hitbox.geometry} material={nodes.About_Hitbox.material} position={[-1.737, 1.952, 0.013]} scale={[0.073, 0.438, 0.613]} />
      <mesh geometry={nodes.About_Hitbox_Anim.geometry} material={nodes.About_Hitbox_Anim.material} position={[-1.664, 2.39, 0.626]} scale={[0.009, 0.009, 0.011]} /> */}
    </group>
  )
}

useGLTF.preload('/models/HomeOffice2_v2.glb')
