/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HomeOffice5_v3.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'
import { gsap } from 'gsap'
import { useNavigate } from 'react-router'

export default function Model(props) {
  let navigate = useNavigate()

  const { nodes, materials, animations } = useGLTF('/models/HomeOffice5_v3.glb')
  const group = React.useRef()
  const whiteMaterial = new THREE.MeshBasicMaterial({ color: 0xffffff})

  const about2AnimRef = useRef()
  const devWork2AnimRef = useRef()
  const animationPairs = {
    About_2_Hitbox: { ref: about2AnimRef },
    Dev_Work_2_Hitbox: { ref: devWork2AnimRef },
    
  }
  const originalScales = {
    About_2_Hitbox: { x: 0.01, y: 0.01, z: 0.01 },
    Dev_Work_2_Hitbox: {x: 0.01, y: 0.01, z: 0.01 }
  };
  // Handle Hover
  const onHover = (key, isHovering) => {
    const animObject = animationPairs[key]
  // Như này to quá
  //   gsap.to(animObject.ref.current.scale, {
  //     x: isHovering ? 1 : 0,
  //     y: isHovering ? 1 : 0,
  //     z: isHovering ? 1 : 0, 
  //     duration: 0.8,
  // })
    const base = originalScales[key];
    gsap.to(animObject.ref.current.scale, {
      x: isHovering ? base.x : 0,
      y: isHovering ? base.y : 0,
      z: isHovering ? base.z : 0,
      duration: 0.8,
    });
  }
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
  Object.values(actions).forEach((action) => {
    action.reset().play()
  })
}, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Wall_corner_shelf" position={[0.433, 1.442, -1.654]} rotation={[1.571, -0.016, 1.573]} scale={[1.605, 1.404, 1.359]}>
          <mesh name="book" geometry={nodes.book.geometry} material={materials['book.024']} position={[-0.048, 0.124, -0.659]} rotation={[-Math.PI / 2, 0, -1.484]} />
          <mesh name="book001" geometry={nodes.book001.geometry} material={materials['book.025']} position={[0.005, 0.115, -0.399]} rotation={[-Math.PI / 2, -0.385, 0]} />
          <mesh name="book002" geometry={nodes.book002.geometry} material={materials['book.026']} position={[0.006, 0.109, -0.384]} rotation={[-Math.PI / 2, -0.385, 0]} />
          <mesh name="book003" geometry={nodes.book003.geometry} material={materials['book.027']} position={[-0.002, 0.109, -0.305]} rotation={[-Math.PI / 2, -0.647, 0]} />
          <mesh name="book004" geometry={nodes.book004.geometry} material={materials['book.028']} position={[0.012, 0.111, -0.365]} rotation={[-Math.PI / 2, -0.385, 0]} />
          <mesh name="book005" geometry={nodes.book005.geometry} material={materials['book.029']} position={[0.004, 0.105, -0.336]} rotation={[-Math.PI / 2, -0.821, 0]} />
          <mesh name="book006" geometry={nodes.book006.geometry} material={materials['book.030']} position={[0.008, 0.106, -0.376]} rotation={[-Math.PI / 2, -0.385, 0]} />
          <mesh name="book007" geometry={nodes.book007.geometry} material={materials['book.031']} position={[0.011, 0.104, -0.35]} rotation={[-Math.PI / 2, -1.012, 0]} />
          <mesh name="book008" geometry={nodes.book008.geometry} material={materials['book.032']} position={[-0.001, 0.1, -0.321]} rotation={[-Math.PI / 2, -0.821, 0]} />
          <mesh name="book009" geometry={nodes.book009.geometry} material={materials['book.033']} position={[-0.003, 0.1, -0.355]} rotation={[-Math.PI / 2, -0.944, 0]} />
          <mesh name="book010" geometry={nodes.book010.geometry} material={materials['book.034']} position={[-0.016, 0.119, -0.682]} rotation={[-Math.PI / 2, 0, -1.331]} />
          <mesh name="book011" geometry={nodes.book011.geometry} material={materials['book.035']} position={[-0.075, 0.126, -0.664]} rotation={[-Math.PI / 2, 0, -1.484]} />
          <mesh name="box002" geometry={nodes.box002.geometry} material={materials['box.003']} position={[0, 0.113, -0.014]} rotation={[-Math.PI / 2, 0.104, 0]}>
            <mesh name="box" geometry={nodes.box.geometry} material={materials['flowers wallpaper.002']} position={[0, 0.041, 0]} rotation={[0, -0.192, 0]}>
              <mesh name="box001" geometry={nodes.box001.geometry} material={materials['blender wallpaper.002']} position={[0, 0.048, 0]} rotation={[0, 0.051, 0]} scale={0.699} />
            </mesh>
          </mesh>
          <mesh name="casket" geometry={nodes.casket.geometry} material={materials['casket_wood.002']} position={[0.001, 0.116, -0.85]} rotation={[-1.571, 1.488, 0]} />
          <mesh name="lock" geometry={nodes.lock.geometry} material={materials['metals.002']} position={[-0.004, 0.179, -0.897]} rotation={[-1.571, 1.488, 0]} />
          <mesh name="shelf001" geometry={nodes.shelf001.geometry} material={materials['wood (Oak Matt Antracite Gray).002']} position={[0, 0.11, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="side_wall" geometry={nodes.side_wall.geometry} material={materials['wood (Oak Matt Antracite Gray).002']} position={[0.11, 0.11, -0.172]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="side_wall001" geometry={nodes.side_wall001.geometry} material={materials['wood (Oak Matt Antracite Gray).002']} position={[-0.097, 0.11, -0.172]} rotation={[Math.PI, 0, -Math.PI / 2]} />
          <mesh name="side_wall002" geometry={nodes.side_wall002.geometry} material={materials['wood (Oak Matt Antracite Gray).002']} position={[0, 0, -0.45]} rotation={[0, 0, -Math.PI]} />
          <mesh name="side_wall003" geometry={nodes.side_wall003.geometry} material={materials['wood (Oak Matt Antracite Gray).002']} position={[0, 0.207, -0.45]} rotation={[Math.PI, 0, 0]} />
          <mesh name="side_wall004" geometry={nodes.side_wall004.geometry} material={materials['wood (Oak Matt Antracite Gray).002']} position={[-0.11, 0.11, -0.729]} rotation={[0, 0, Math.PI / 2]} />
          <mesh name="side_wall005" geometry={nodes.side_wall005.geometry} material={materials['wood (Oak Matt Antracite Gray).002']} position={[0.097, 0.11, -0.729]} rotation={[Math.PI, 0, Math.PI / 2]} />
        </group>
        <group name="Empty007" position={[-0.142, 1.713, -1.677]} scale={[1.472, 1.425, 1.683]}>
          <group name="Cube067" position={[-0.033, 0.126, 0.006]} rotation={[1.573, -0.183, -1.563]} scale={0.937}>
            <mesh name="Cube152" geometry={nodes.Cube152.geometry} material={materials['book cover.008']} />
            <mesh name="Cube152_1" geometry={nodes.Cube152_1.geometry} material={materials['stacked paper.008']} />
          </group>
          <group name="Cube068" position={[-0.017, 0.128, 0.005]} rotation={[1.572, -0.181, -1.562]} scale={0.937}>
            <mesh name="Cube153" geometry={nodes.Cube153.geometry} material={materials['book cover.008']} />
            <mesh name="Cube153_1" geometry={nodes.Cube153_1.geometry} material={materials['stacked paper.008']} />
          </group>
          <group name="Cube069" position={[-0.053, 0.129, 0.007]} rotation={[1.572, -0.184, -1.563]} scale={0.937}>
            <mesh name="Cube154" geometry={nodes.Cube154.geometry} material={materials['book cover.008']} />
            <mesh name="Cube154_1" geometry={nodes.Cube154_1.geometry} material={materials['stacked paper.008']} />
          </group>
          <group name="Cube070" position={[-0.153, 0.121, 0.008]} rotation={[1.565, -0.343, -1.566]} scale={0.937}>
            <mesh name="Cube155" geometry={nodes.Cube155.geometry} material={materials['book cover.009']} />
            <mesh name="Cube155_1" geometry={nodes.Cube155_1.geometry} material={materials['stacked paper.009']} />
          </group>
          <group name="Cube071" position={[-0.135, 0.126, 0.004]} rotation={[1.574, -0.339, -1.563]} scale={0.937}>
            <mesh name="Cube156" geometry={nodes.Cube156.geometry} material={materials['book cover.008']} />
            <mesh name="Cube156_1" geometry={nodes.Cube156_1.geometry} material={materials['stacked paper.008']} />
          </group>
          <group name="Cube072" position={[-0.088, 0.11, -0.001]} rotation={[1.575, -0.323, -1.563]} scale={0.937}>
            <mesh name="Cube157" geometry={nodes.Cube157.geometry} material={materials['book cover.008']} />
            <mesh name="Cube157_1" geometry={nodes.Cube157_1.geometry} material={materials['stacked paper.008']} />
          </group>
          <group name="Cube073" position={[-0.098, 0.124, 0.004]} rotation={[1.571, -0.337, -1.564]} scale={0.937}>
            <mesh name="Cube158" geometry={nodes.Cube158.geometry} material={materials['book cover.008']} />
            <mesh name="Cube158_1" geometry={nodes.Cube158_1.geometry} material={materials['stacked paper.008']} />
          </group>
          <group name="Cube074" position={[-0.114, 0.123, 0.007]} rotation={[1.573, -0.338, -1.564]} scale={0.937}>
            <mesh name="Cube159" geometry={nodes.Cube159.geometry} material={materials['book cover.008']} />
            <mesh name="Cube159_1" geometry={nodes.Cube159_1.geometry} material={materials['stacked paper.008']} />
          </group>
          <group name="Cube075" position={[-0.176, 0.115, 0.011]} rotation={[1.573, -0.44, -1.564]} scale={0.897}>
            <mesh name="Cube160" geometry={nodes.Cube160.geometry} material={materials['book cover.008']} />
            <mesh name="Cube160_1" geometry={nodes.Cube160_1.geometry} material={materials['stacked paper.008']} />
          </group>
        </group>
        <group name="Low_Poly_Flower_Vase" position={[-1.481, 0.982, -0.004]} scale={[0.365, 0.353, 0.417]}>
          <mesh name="Vase" geometry={nodes.Vase.geometry} material={materials['Flower Vase_Color.002']} scale={1.345} />
        </group>
        <group name="Empty006" position={[-1.342, 1.747, -1.629]} scale={[1.412, 1.367, 1.614]}>
          <group name="Empty003" position={[0.244, 0, 0.01]} scale={0.297} />
          <group name="Cube106" position={[0.18, 0.097, 0.007]} rotation={[1.563, 0.425, -1.553]} scale={1.045}>
            <mesh name="Cube161" geometry={nodes.Cube161.geometry} material={materials['book cover.010']} />
            <mesh name="Cube161_1" geometry={nodes.Cube161_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube107" position={[0.389, 0.112, 0.009]} rotation={[1.562, 0.482, -1.551]} scale={1.045}>
            <mesh name="Cube162" geometry={nodes.Cube162.geometry} material={materials['book cover.010']} />
            <mesh name="Cube162_1" geometry={nodes.Cube162_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube108" position={[0.421, 0.106, 0.003]} rotation={[1.579, 0.554, -1.559]} scale={1.045}>
            <mesh name="Cube163" geometry={nodes.Cube163.geometry} material={materials['book cover.010']} />
            <mesh name="Cube163_1" geometry={nodes.Cube163_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube109" position={[0.16, 0.1, 0.005]} rotation={[1.565, 0.418, -1.557]} scale={1.045}>
            <mesh name="Cube164" geometry={nodes.Cube164.geometry} material={materials['book cover.010']} />
            <mesh name="Cube164_1" geometry={nodes.Cube164_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube110" position={[0.14, 0.088, -0.003]} rotation={[1.567, 0.372, -1.562]} scale={1.045}>
            <mesh name="Cube165" geometry={nodes.Cube165.geometry} material={materials['book cover.010']} />
            <mesh name="Cube165_1" geometry={nodes.Cube165_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube111" position={[0.362, 0.114, 0.007]} rotation={[1.558, 0.479, -1.55]} scale={1.045}>
            <mesh name="Cube166" geometry={nodes.Cube166.geometry} material={materials['book cover.010']} />
            <mesh name="Cube166_1" geometry={nodes.Cube166_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube112" position={[0.108, 0.116, -0.003]} rotation={[1.57, 0.318, -1.57]} scale={1.045}>
            <mesh name="Cube167" geometry={nodes.Cube167.geometry} material={materials['book cover.011']} />
            <mesh name="Cube167_1" geometry={nodes.Cube167_1.geometry} material={materials['stacked paper.011']} />
          </group>
          <group name="Cube113" position={[0.26, 0.111, 0.006]} rotation={[1.568, 0.439, -1.554]} scale={1.045}>
            <mesh name="Cube168" geometry={nodes.Cube168.geometry} material={materials['book cover.011']} />
            <mesh name="Cube168_1" geometry={nodes.Cube168_1.geometry} material={materials['stacked paper.011']} />
          </group>
          <group name="Cube114" position={[0.277, 0.116, -0.002]} rotation={[1.566, 0.441, -1.555]} scale={1.045}>
            <mesh name="Cube169" geometry={nodes.Cube169.geometry} material={materials['book cover.010']} />
            <mesh name="Cube169_1" geometry={nodes.Cube169_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube115" position={[0.057, 0.091, 0.008]} rotation={[1.57, 0.005, -1.573]} scale={1.045}>
            <mesh name="Cube170" geometry={nodes.Cube170.geometry} material={materials['book cover.010']} />
            <mesh name="Cube170_1" geometry={nodes.Cube170_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube116" position={[0.346, 0.098, -0.003]} rotation={[1.56, 0.461, -1.551]} scale={1.045}>
            <mesh name="Cube171" geometry={nodes.Cube171.geometry} material={materials['book cover.010']} />
            <mesh name="Cube171_1" geometry={nodes.Cube171_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube117" position={[0.322, 0.112, -0.001]} rotation={[1.565, 0.443, -1.553]} scale={1.045}>
            <mesh name="Cube172" geometry={nodes.Cube172.geometry} material={materials['book cover.010']} />
            <mesh name="Cube172_1" geometry={nodes.Cube172_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube118" position={[0.302, 0.114, 0.006]} rotation={[1.564, 0.444, -1.553]} scale={1.045}>
            <mesh name="Cube173" geometry={nodes.Cube173.geometry} material={materials['book cover.010']} />
            <mesh name="Cube173_1" geometry={nodes.Cube173_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube119" position={[0.099, 0.101, -0.002]} rotation={[1.572, 0.319, -1.571]} scale={1.045}>
            <mesh name="Cube174" geometry={nodes.Cube174.geometry} material={materials['book cover.010']} />
            <mesh name="Cube174_1" geometry={nodes.Cube174_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube120" position={[0.043, 0.1, 0.006]} rotation={[1.571, 0.003, -1.572]}>
            <mesh name="Cube175" geometry={nodes.Cube175.geometry} material={materials['book cover.010']} />
            <mesh name="Cube175_1" geometry={nodes.Cube175_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube121" position={[0.23, 0.109, 0.004]} rotation={[1.562, 0.431, -1.548]}>
            <mesh name="Cube176" geometry={nodes.Cube176.geometry} material={materials['book cover.010']} />
            <mesh name="Cube176_1" geometry={nodes.Cube176_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube122" position={[0.249, 0.108, 0.007]} rotation={[1.571, 0.439, -1.555]}>
            <mesh name="Cube177" geometry={nodes.Cube177.geometry} material={materials['book cover.010']} />
            <mesh name="Cube177_1" geometry={nodes.Cube177_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube123" position={[0.027, 0.1, 0.017]} rotation={[1.571, 0.003, -1.57]}>
            <mesh name="Cube178" geometry={nodes.Cube178.geometry} material={materials['book cover.010']} />
            <mesh name="Cube178_1" geometry={nodes.Cube178_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube124" position={[0.008, 0.087, 0.014]} rotation={[1.571, 0.003, -1.57]}>
            <mesh name="Cube179" geometry={nodes.Cube179.geometry} material={materials['book cover.010']} />
            <mesh name="Cube179_1" geometry={nodes.Cube179_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube125" position={[0.206, 0.111, 0.001]} rotation={[1.563, 0.432, -1.552]}>
            <mesh name="Cube180" geometry={nodes.Cube180.geometry} material={materials['book cover.010']} />
            <mesh name="Cube180_1" geometry={nodes.Cube180_1.geometry} material={materials['stacked paper.010']} />
          </group>
          <group name="Cube126" position={[0.191, 0.107, 0.003]} rotation={[1.562, 0.429, -1.549]}>
            <mesh name="Cube181" geometry={nodes.Cube181.geometry} material={materials['book cover.011']} />
            <mesh name="Cube181_1" geometry={nodes.Cube181_1.geometry} material={materials['stacked paper.011']} />
          </group>
        </group>
        <group name="IMac_computer" position={[-0.674, 1.154, -1.407]} rotation={[0, -0.033, 0]} scale={[1.172, 1.134, 1.339]}>
          <group name="Apple_iMac" rotation={[0, -1.554, 0]}>
            <mesh name="Untitled002" geometry={nodes.Untitled002.geometry} material={materials['aluminium.002']} />
            <mesh name="Untitled002_1" geometry={nodes.Untitled002_1.geometry} material={materials['rubber.003']} />
            <mesh name="Untitled002_2" geometry={nodes.Untitled002_2.geometry} material={materials['black plastic.002']} />
            <mesh name="Untitled002_3" geometry={nodes.Untitled002_3.geometry} material={materials['glass.004']} />
            <mesh name="Untitled002_4" geometry={nodes.Untitled002_4.geometry} material={materials['glass frame.002']} />
            <mesh name="Untitled002_5" geometry={nodes.Untitled002_5.geometry} material={materials['display frame.002']} />
            <mesh name="Untitled002_6" geometry={nodes.Untitled002_6.geometry} material={materials['display.002']} />
            <mesh name="Untitled002_7" geometry={nodes.Untitled002_7.geometry} material={materials['white plastic.002']} />
            <mesh name="Untitled002_8" geometry={nodes.Untitled002_8.geometry} material={materials['metal.006']} />
            <mesh name="Untitled002_9" geometry={nodes.Untitled002_9.geometry} material={materials['yellow metal.002']} />
            <mesh name="Untitled002_10" geometry={nodes.Untitled002_10.geometry} material={materials['camera.002']} />
            <mesh name="Untitled002_11" geometry={nodes.Untitled002_11.geometry} material={materials['keys left.002']} />
            <mesh name="Untitled002_12" geometry={nodes.Untitled002_12.geometry} material={materials['glossy white plastic.002']} />
            <mesh name="Untitled002_13" geometry={nodes.Untitled002_13.geometry} material={materials['matt white plastic.002']} />
            <mesh name="Untitled002_14" geometry={nodes.Untitled002_14.geometry} material={materials['rubber.004']} />
            <mesh name="Untitled002_15" geometry={nodes.Untitled002_15.geometry} material={materials['plastic black.002']} />
            <mesh name="Untitled002_16" geometry={nodes.Untitled002_16.geometry} material={materials['plastic green.002']} />
            <mesh name="Untitled002_17" geometry={nodes.Untitled002_17.geometry} material={materials['switch top.002']} />
            <mesh name="Untitled002_18" geometry={nodes.Untitled002_18.geometry} material={materials['chrome.002']} />
            <mesh name="Untitled002_19" geometry={nodes.Untitled002_19.geometry} material={materials['plastic top.002']} />
          </group>
        </group>
        <group name="Table_Lamp" position={[-1.4, 1.193, -1.185]} scale={[0.765, 0.741, 0.874]}>
          <mesh name="Bulb" geometry={nodes.Bulb.geometry} material={materials['Bulb.002']} position={[0, 0.568, 0]} />
          <group name="Lamp_Body">
            <mesh name="Cylinder034" geometry={nodes.Cylinder034.geometry} material={materials['Metal_Base.002']} />
            <mesh name="Cylinder034_1" geometry={nodes.Cylinder034_1.geometry} material={materials['Material.039']} />
          </group>
          <mesh name="Lamp_Cover" geometry={nodes.Lamp_Cover.geometry} material={materials['Lamp Cover.002']} position={[0, 0.51, 0]} scale={[1.1, 1, 1.1]} />
          <mesh name="Wire" geometry={nodes.Wire.geometry} material={materials['Wire.002']} position={[0.012, 0, 0.029]} rotation={[-Math.PI, 1.178, -Math.PI]} scale={0.9} />
        </group>
        <group name="Modular_plant" position={[0.155, 1.148, -1.373]} scale={[0.176, 0.171, 0.201]}>
          <group name="Empty001" position={[-0.035, 0.092, 0.039]} rotation={[0, 1.323, 0]} scale={0.557} />
          <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Ceramic Glazed.002']} position={[-0.035, 0.91, 0.039]} scale={0.588} />
          <mesh name="FEUILLE001" geometry={nodes.FEUILLE001.geometry} material={materials['Material.040']} position={[-0.035, 0.039, 0.039]} scale={0.588} />
          <mesh name="pebble545" geometry={nodes.pebble545.geometry} material={materials['rock wall.002']} position={[-0.05, 0.851, 0.027]} rotation={[2.858, -1.017, 0.183]} scale={0.588} />
        </group>
        <group name="Bookcase_01" position={[-1.476, 0.263, 1.611]} rotation={[0, 1.562, 0]} scale={[1.297, 1.099, 1.135]}>
          <group name="BOOK1" scale={0.207}>
            <mesh name="Plane060" geometry={nodes.Plane060.geometry} material={materials['GREY.002']} />
            <mesh name="Plane060_1" geometry={nodes.Plane060_1.geometry} material={materials['BLACK-PLASTIC.002']} />
            <mesh name="Plane060_2" geometry={nodes.Plane060_2.geometry} material={materials['WHITE.002']} />
            <group name="BOOK2" scale={4.825}>
              <mesh name="Plane061" geometry={nodes.Plane061.geometry} material={materials['MAROON.002']} />
              <mesh name="Plane061_1" geometry={nodes.Plane061_1.geometry} material={materials['GOLD.002']} />
              <mesh name="Plane061_2" geometry={nodes.Plane061_2.geometry} material={materials['WHITE.002']} />
            </group>
            <group name="BOOK3" scale={4.825}>
              <mesh name="Plane062" geometry={nodes.Plane062.geometry} material={materials['CREAM.002']} />
              <mesh name="Plane062_1" geometry={nodes.Plane062_1.geometry} material={materials['WHITE.002']} />
            </group>
            <group name="BOOK4" scale={4.825}>
              <mesh name="Plane063" geometry={nodes.Plane063.geometry} material={materials['BLACK-PLASTIC.002']} />
              <mesh name="Plane063_1" geometry={nodes.Plane063_1.geometry} material={materials['WHITE.002']} />
            </group>
            <group name="BOOK5" scale={4.825}>
              <mesh name="Plane064" geometry={nodes.Plane064.geometry} material={materials['LIME.002']} />
              <mesh name="Plane064_1" geometry={nodes.Plane064_1.geometry} material={materials['RED.002']} />
              <mesh name="Plane064_2" geometry={nodes.Plane064_2.geometry} material={materials['WHITE.002']} />
            </group>
          </group>
          <group name="BOOKSET" scale={0.207}>
            <mesh name="Plane065" geometry={nodes.Plane065.geometry} material={materials['GREY.002']} />
            <mesh name="Plane065_1" geometry={nodes.Plane065_1.geometry} material={materials['BLACK-PLASTIC.002']} />
            <mesh name="Plane065_2" geometry={nodes.Plane065_2.geometry} material={materials['WHITE.002']} />
          </group>
          <mesh name="BOOKSHELF01" geometry={nodes.BOOKSHELF01.geometry} material={materials['CREAM-WOOD-TEXTURE.002']} scale={0.207}>
            <mesh name="TRANSPARENT-GLASS" geometry={nodes['TRANSPARENT-GLASS'].geometry} material={materials['GLASS.002']} position={[-1.125, 3.403, 0]} rotation={[0, 0, -Math.PI / 2]} scale={1.024} />
            <mesh name="TRANSPARENT-GLASS-FRAME" geometry={nodes['TRANSPARENT-GLASS-FRAME'].geometry} material={materials['BLACK-PLASTIC.002']} position={[-1.127, 3.402, 0]} rotation={[0, 0, -Math.PI / 2]} />
          </mesh>
          <group name="CANDLE01" scale={0.207}>
            <mesh name="Cylinder036" geometry={nodes.Cylinder036.geometry} material={materials['CYAN.002']} />
            <mesh name="Cylinder036_1" geometry={nodes.Cylinder036_1.geometry} material={materials['BLACK-PLASTIC.002']} />
          </group>
          <group name="CANDLE02" scale={0.207}>
            <mesh name="Cylinder037" geometry={nodes.Cylinder037.geometry} material={materials['CYAN.002']} />
            <mesh name="Cylinder037_1" geometry={nodes.Cylinder037_1.geometry} material={materials['BLACK-PLASTIC.002']} />
          </group>
          <group name="CHEST" scale={0.207}>
            <mesh name="Cube183" geometry={nodes.Cube183.geometry} material={materials['RED.002']} />
            <mesh name="Cube183_1" geometry={nodes.Cube183_1.geometry} material={materials['GOLD.002']} />
            <group name="CHEST-CAP" scale={4.825}>
              <mesh name="Cube184" geometry={nodes.Cube184.geometry} material={materials['GOLD.002']} />
              <mesh name="Cube184_1" geometry={nodes.Cube184_1.geometry} material={materials['RED.002']} />
            </group>
            <mesh name="CHEST-LEATHER" geometry={nodes['CHEST-LEATHER'].geometry} material={materials['RED.002']} scale={4.825} />
          </group>
          <mesh name="CONTAINER01" geometry={nodes.CONTAINER01.geometry} material={materials['WHITE.002']} scale={0.207}>
            <mesh name="CAPE01" geometry={nodes.CAPE01.geometry} material={materials['GOLD.002']} scale={4.825} />
          </mesh>
          <mesh name="CONTAINER02" geometry={nodes.CONTAINER02.geometry} material={materials['WHITE.002']} scale={0.207}>
            <mesh name="CAPE02" geometry={nodes.CAPE02.geometry} material={materials['GOLD.002']} scale={4.825} />
          </mesh>
          <mesh name="DECORATION" geometry={nodes.DECORATION.geometry} material={materials['GOLD.002']} scale={0.207} />
          <mesh name="FRAME01" geometry={nodes.FRAME01.geometry} material={materials['BLACK-PLASTIC.002']} scale={0.207}>
            <mesh name="PHOTO01" geometry={nodes.PHOTO01.geometry} material={materials['PHOTO01.002']} scale={4.825} />
          </mesh>
          <mesh name="FRAME02" geometry={nodes.FRAME02.geometry} material={materials['BLACK-PLASTIC.002']} scale={0.207}>
            <mesh name="PHOTO02" geometry={nodes.PHOTO02.geometry} material={materials['PHOTO02.002']} scale={4.825} />
          </mesh>
          <mesh name="LAMP" geometry={nodes.LAMP.geometry} material={materials['SILVER.002']} scale={0.207}>
            <mesh name="BULB001" geometry={nodes.BULB001.geometry} material={materials['LED.002']} scale={4.825} />
            <mesh name="CASING001" geometry={nodes.CASING001.geometry} material={materials['GOLD.002']} scale={4.825} />
            <mesh name="POLE" geometry={nodes.POLE.geometry} material={materials['SILVER.002']} scale={4.825} />
          </mesh>
          <group name="RUBIC-CUBE" scale={0.207}>
            <mesh name="Cube186" geometry={nodes.Cube186.geometry} material={materials['WHITE.002']} />
            <mesh name="Cube186_1" geometry={nodes.Cube186_1.geometry} material={materials['RED.002']} />
            <mesh name="Cube186_2" geometry={nodes.Cube186_2.geometry} material={materials['YELLOW.002']} />
            <mesh name="Cube186_3" geometry={nodes.Cube186_3.geometry} material={materials['LIME.002']} />
            <mesh name="Cube186_4" geometry={nodes.Cube186_4.geometry} material={materials['BLUE.002']} />
            <mesh name="Cube186_5" geometry={nodes.Cube186_5.geometry} material={materials['ORANGE.002']} />
            <mesh name="Cube186_6" geometry={nodes.Cube186_6.geometry} material={materials['PURPLE.002']} />
          </group>
        </group>
        <group name="Brown_and_beige_Rug001" position={[0.748, 0.362, 0.772]} scale={[0.376, 0.364, 0.366]}>
          <group name="Curves_32" position={[0, 0.005, 0]} />
          <mesh name="Tapis_32" geometry={nodes.Tapis_32.geometry} material={materials['tapis 32.002']} position={[0, -0.29, 0]} scale={3.024} />
        </group>
        <group name="Marble_Round_Table" position={[0.954, 0.276, 0.735]} scale={[0.711, 0.688, 0.813]}>
          <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['American Oak.002']} scale={[0.499, 0.622, 0.499]} />
          <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['American Oak.002']} position={[0, 0.711, 0]} scale={[0.499, 0.622, 0.499]} />
          <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={materials['Carrara Marble.002']} position={[0, 0.768, 0]} scale={0.906} />
          <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['American Oak.002']} position={[0, 0.03, 0]} rotation={[Math.PI, -0.175, Math.PI]} scale={[0.621, 0.774, 0.556]} />
        </group>
        <group name="Plant001" position={[1.322, 0.26, -1.254]} scale={[1.032, 0.999, 1.18]}>
          <mesh name="PlantMonstera" geometry={nodes.PlantMonstera.geometry} material={materials['Plant.002']} scale={0.736} />
          <mesh name="Clay" geometry={nodes.Clay.geometry} material={materials['BrownClay.002']} />
          <mesh name="Vase001" geometry={nodes.Vase001.geometry} material={materials['Clay Gray.002']} />
        </group>
        <group name="Back-Wing_Chair" position={[-0.578, 2.086, -0.939]} rotation={[0, -0.063, 0]} scale={[1.998, 1.932, 2.281]} />
        <pointLight name="Point" intensity={8} decay={3} distance={20}  color="#fff3dd" position={[-0.008, 3.282, 0.008]} rotation={[-Math.PI / 2, 0, 0]} />
        <pointLight name="Point001" intensity={8} decay={2.5} distance={20}  color="#fff3dd" position={[-0.008, 2.327, 0.008]} rotation={[-Math.PI / 2, 0, 0]} />
        <pointLight name="Point002" intensity={8} decay={3} distance={20}  color="#fff3dd" position={[2.815, 2.076, 0.008]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Globe_inner_pin001" geometry={nodes.Globe_inner_pin001.geometry} material={materials['stainless.002']} position={[0.191, -0.011, 0.448]} rotation={[0, 0, -Math.PI / 2]} scale={[1.932, 1.996, 2.282]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Beige Marble floor.002']} position={[0.191, 0.019, 0.448]} scale={[1.996, 1.143, 2.282]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.036']} position={[0.191, 1.962, 0.448]} scale={[1.996, 1.932, 2.282]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.037']} position={[0.213, 0.019, 0.423]} scale={[28.862, 16.535, 32.991]} />
        <group name="Corner_desk" position={[-0.623, 0.244, -0.708]} rotation={[0, 1.562, 0]} scale={[1.461, 1.238, 1.581]}>
          <mesh name="Cube142" geometry={nodes.Cube142.geometry} material={materials['wood.003']} />
          <mesh name="Cube142_1" geometry={nodes.Cube142_1.geometry} material={materials['white paint.003']} />
          <mesh name="Cube142_2" geometry={nodes.Cube142_2.geometry} material={materials['metal.004']} />
          <group name="Cube006" position={[0.118, 0.399, -0.503]} rotation={[0, 0.14, 0]}>
            <mesh name="Cube143" geometry={nodes.Cube143.geometry} material={materials['cover.003']} />
            <mesh name="Cube143_1" geometry={nodes.Cube143_1.geometry} material={materials['pages.003']} />
          </group>
          <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['white paint.003']} position={[-0.122, 0.041, -0.548]} rotation={[0, -1.571, 0]} scale={[0.137, 0.102, 0.137]}>
            <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Woven Rattan Pattern.003']} />
          </mesh>
          <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['white paint.003']} position={[0.104, 0.041, -0.534]} rotation={[Math.PI, -1.553, Math.PI]} scale={[0.137, 0.102, 0.137]}>
            <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Woven Rattan Pattern.003']} />
          </mesh>
          <group name="Plane008" position={[-0.103, 0.604, -0.532]} rotation={[0, 0.042, 0]}>
            <mesh name="Plane056" geometry={nodes.Plane056.geometry} material={materials['Metal wire mesh.003']} />
            <mesh name="Plane056_1" geometry={nodes.Plane056_1.geometry} material={materials['metal.004']} />
            <group name="Plane003" position={[-0.001, 0.032, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[0.149, 1, 0.105]}>
              <mesh name="Plane057" geometry={nodes.Plane057.geometry} material={materials['pages.003']} />
              <mesh name="Plane057_1" geometry={nodes.Plane057_1.geometry} material={materials['Material.038']} />
            </group>
            <group name="Plane010" position={[0.002, 0.028, 0]}>
              <mesh name="Plane058" geometry={nodes.Plane058.geometry} material={materials['pages.003']} />
              <mesh name="Plane058_1" geometry={nodes.Plane058_1.geometry} material={materials['color.003']} />
              <mesh name="Plane058_2" geometry={nodes.Plane058_2.geometry} material={nodes.Plane058_2.material} />
              <mesh name="Plane058_3" geometry={nodes.Plane058_3.geometry} material={materials['metal.004']} />
            </group>
          </group>
          <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['cover.003']} position={[-0.681, 0.008, -0.371]} scale={0.026} />
          <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['metal.004']} position={[-0.076, 0.399, -0.461]} scale={0.051} />
        </group>
        <mesh name="Hanging_shelf" geometry={nodes.Hanging_shelf.geometry} material={materials['Desk wood.003']} position={[-0.776, 2.139, -1.816]} rotation={[1.533, 0, 0]} scale={[1.958, 1.679, 1.582]} />
        <mesh name="Old_ceramic_vase" geometry={nodes.Old_ceramic_vase.geometry} material={materials['marble (cracked).002']} position={[-0.742, 1.731, -1.632]} scale={[1.996, 1.932, 2.282]} />
        <mesh name="Picture_frame002" geometry={nodes.Picture_frame002.geometry} material={materials['Material.041']} position={[-1.788, 2.163, -0.262]} rotation={[1.57, -0.008, -1.538]} scale={[1.884, 1.649, 1.596]} />
        <mesh name="Circular_Leather_Pillow" geometry={nodes.Circular_Leather_Pillow.geometry} material={materials['Material.042']} position={[0.993, 0.27, 1.502]} scale={[1.996, 1.932, 2.282]} />
        <mesh name="Globe_-_Blue_White" geometry={nodes['Globe_-_Blue_White'].geometry} material={materials['globe texture.002']} position={[1.033, 0.819, 0.792]} scale={[1.5, 1.715, 1.715]}>
          <mesh name="Globe_holder" geometry={nodes.Globe_holder.geometry} material={materials['stainless.003']} rotation={[Math.PI / 2, -0.549, Math.PI]} />
          <mesh name="Globe_inner_pin" geometry={nodes.Globe_inner_pin.geometry} material={materials['stainless.003']} rotation={[0, 0, -0.549]} />
          <mesh name="Globe_inner_pin002" geometry={nodes.Globe_inner_pin002.geometry} material={materials['stainless.003']} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Globe_inner_pin003" geometry={nodes.Globe_inner_pin003.geometry} material={materials['stainless.003']} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="outer_holder" geometry={nodes.outer_holder.geometry} material={materials['stainless.003']} rotation={[Math.PI / 2, 0, 0]} />
        </mesh>
                <mesh
        geometry={nodes.About_2_Hitbox.geometry}
        material={nodes.About_2_Hitbox.material}
        visible={false}
        position={[-1.734, 2.163, -0.262]}
        scale={[0.061, 0.347, 0.575]}
        onPointerOver={() => {
          onHover("About_2_Hitbox", true)
          document.body.style.cursor = "pointer"
        }}
        onPointerOut={() => {
          onHover("About_2_Hitbox", false)
          document.body.style.cursor = "auto"
        }}
        onClick={() => {
          // openPanel("About_2_Hitbox")
          navigate("/about-2")
        }}
         />
      <mesh
        ref={about2AnimRef}
        geometry={nodes.About_2_Hitbox_Anim.geometry}
        material={whiteMaterial}
        position={[-1.673, 2.51, 0.313]}
        scale={0.01}
         />
      <mesh
        geometry={nodes.Dev_Work_2_Hitbox.geometry}
        material={nodes.Dev_Work_2_Hitbox.material}
        position={[0.715, 0.821, 0.826]}
        visible={false}
        scale={[0.887, 0.552, 1.217]}
        onPointerOver={() => {
          onHover("Dev_Work_2_Hitbox", true)
          document.body.style.cursor = "pointer"
        }}
        onPointerOut={() => {
          onHover("Dev_Work_2_Hitbox", false)
          document.body.style.cursor = "auto"
        }}
        onClick={() => {
          // openPanel("Dev_Work_2_Hitbox")
          navigate("/dev-work-2")
        }}
         />
      <mesh
        ref={devWork2AnimRef}
        geometry={nodes.Dev_Work_2_Hitbox_Anim.geometry}
        material={whiteMaterial}
        position={[1.602, 1.373, 2.044]}
        scale={0.01}
        />
        {/* <mesh name="Dev_Work_2_Hitbox" geometry={nodes.Dev_Work_2_Hitbox.geometry} material={nodes.Dev_Work_2_Hitbox.material} position={[0.715, 0.821, 0.826]} scale={[0.887, 0.552, 1.217]} />
        <mesh name="Dev_Work_2_Hitbox_Anim" geometry={nodes.Dev_Work_2_Hitbox_Anim.geometry} material={nodes.Dev_Work_2_Hitbox_Anim.material} position={[1.602, 1.373, 2.044]} scale={0.01} />
        <mesh name="About_2_Hitbox" geometry={nodes.About_2_Hitbox.geometry} material={nodes.About_2_Hitbox.material} position={[-1.734, 2.163, -0.262]} scale={[0.061, 0.347, 0.575]} />
        <mesh name="About_2_Hitbox_Anim" geometry={nodes.About_2_Hitbox_Anim.geometry} material={nodes.About_2_Hitbox_Anim.material} position={[-1.673, 2.51, 0.313]} scale={0.01} /> */}
        <group name="Office_Chair_REX" position={[-0.43, 0.269, -0.492]} rotation={[Math.PI, -0.268, Math.PI]} scale={[1.394, 1.224, 1.378]}>
          <mesh name="Plane082" geometry={nodes.Plane082.geometry} material={materials['Office Chair_Fabric.002']} />
          <mesh name="Plane082_1" geometry={nodes.Plane082_1.geometry} material={materials['Office Chair_Metal.002']} />
          <mesh name="Plane082_2" geometry={nodes.Plane082_2.geometry} material={materials['Office Chair_Painted Metal.002']} />
          <mesh name="Plane082_3" geometry={nodes.Plane082_3.geometry} material={materials['Office Chair_Plastic.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/HomeOffice5_v3.glb')
