/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/HomeOffice2_v5.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'
import { gsap } from 'gsap'
import { useNavigate } from 'react-router'

export default function Model(props) {
  let navigate = useNavigate()

  const { nodes, materials, animations } = useGLTF('/models/HomeOffice2_v5.glb')
  const group = React.useRef()
  const whiteMaterial = new THREE.MeshBasicMaterial({ color: 0xffffff})

  const aboutAnimRef = useRef()
  const devWorkAnimRef = useRef()
  const animationPairs = {
    About_Hitbox: { ref: aboutAnimRef },
    Dev_Work_Hitbox: { ref: devWorkAnimRef },
    
  }
  const originalScales = {
    About_Hitbox: { x: 0.009, y: 0.009, z: 0.011 },
    Dev_Work_Hitbox: {x: 0.018, y: 0.018, z: 0.021 }
  };
  // Handle Hover
  const onHover = (key, isHovering) => {
    const animObject = animationPairs[key]
  // Như này to quá
  //   gsap.to(animObject.ref.current.scale, {
  //     x: isHovering ? 1 : 0,
  //     y: isHovering ? 1 : 0,
  //     z: isHovering ? 1 : 0, 
  //     duration: 0.8,
  // })
    const base = originalScales[key];
    gsap.to(animObject.ref.current.scale, {
      x: isHovering ? base.x : 0,
      y: isHovering ? base.y : 0,
      z: isHovering ? base.z : 0,
      duration: 0.8,
      ease: "power1.out"
    });
  }
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
  Object.values(actions).forEach((action) => {
    action.reset().play()
  })
}, [actions]) 
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Salanga_Table_Lamp" position={[0.896, 0.956, 1.121]} scale={[1.33, 1.33, 1.54]} />
        <group name="Stacked_set_of_books" position={[0.72, 1.021, 0.813]} rotation={[0, -0.276, 0]} scale={[1.268, 1.252, 1.436]} />
        <group name="2_panel_sliding_window" position={[0.069, 0.999, -2.056]} scale={[1.45, 1.45, 1.679]} />
        <group name="Floating_shelf_with_decoration" position={[-1.831, 1.669, 1.015]} rotation={[1.58, 0.011, -1.493]} scale={[2.112, 1.827, 1.825]}>
          <group name="Cube007" position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Cube012_1" geometry={nodes.Cube012_1.geometry} material={materials['Material.009']} />
            <mesh name="Cube012_2" geometry={nodes.Cube012_2.geometry} material={materials['paper.001']} />
          </group>
          <group name="Cube008" position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={materials['Material.010']} />
            <mesh name="Cube013_2" geometry={nodes.Cube013_2.geometry} material={materials['paper.001']} />
          </group>
          <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Ground.001']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Ceramica off white.002']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Vidro colorido.002']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <group name="Cylinder001" position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Mesh026" geometry={nodes.Mesh026.geometry} material={materials['Candle Wax.001']} />
            <mesh name="Mesh026_1" geometry={nodes.Mesh026_1.geometry} material={materials['Rope.001']} />
          </group>
          <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Vidro.002']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <group name="Cylinder007" position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Mesh028" geometry={nodes.Mesh028.geometry} material={materials['Wood.003']} />
            <mesh name="Mesh028_1" geometry={nodes.Mesh028_1.geometry} material={materials['Material.011']} />
          </group>
          <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials['Vidro colorido.002']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials['Material.012']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="shelf" geometry={nodes.shelf.geometry} material={materials['laqueado brilhoso branco.001']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="Likestone_Sofa" position={[0.132, 0.092, -1.54]} scale={[1.045, 1.045, 1.21]}>
          <mesh name="Buttons" geometry={nodes.Buttons.geometry} material={materials['Material.013']} position={[0, -0.001, 0]} />
          <mesh name="Sofa_frame" geometry={nodes.Sofa_frame.geometry} material={materials['Material.014']} position={[0.018, -0.12, 0.032]} />
        </group>
        <group name="Belfield_L-Shape_Desk" position={[0.361, 0.128, 0.751]} rotation={[0, -1.551, 0]} scale={[1.243, 1.074, 1.074]}>
          <mesh name="Desk_Side" geometry={nodes.Desk_Side.geometry} material={materials['Wood Parquet.001']} />
          <mesh name="Desk_Spacer" geometry={nodes.Desk_Spacer.geometry} material={materials['Wood Parquet.001']} />
          <mesh name="Desk_Top" geometry={nodes.Desk_Top.geometry} material={materials['Wood dark.001']} />
          <mesh name="Drawer_Bottom" geometry={nodes.Drawer_Bottom.geometry} material={materials['White Wood.001']} />
          <mesh name="Drawer_Top" geometry={nodes.Drawer_Top.geometry} material={materials['Wood Parquet.001']} />
          <mesh name="Drawers_Back" geometry={nodes.Drawers_Back.geometry} material={materials['Wood Parquet.001']} />
          <mesh name="Drawers_Sides" geometry={nodes.Drawers_Sides.geometry} material={materials['Wood dark.001']} />
          <mesh name="Drawers_Spacer" geometry={nodes.Drawers_Spacer.geometry} material={materials['Material.017']} />
          <mesh name="Drawers_Top" geometry={nodes.Drawers_Top.geometry} material={materials['Wood Parquet.001']} />
        </group>
        <group name="Belfield_L-Shape_Desk001" position={[0.361, 0.128, 0.751]} rotation={[0, -1.551, 0]} scale={[1.243, 1.074, 1.074]}>
          <mesh name="Desk_Side001" geometry={nodes.Desk_Side001.geometry} material={materials['Wood Parquet.001']} />
          <mesh name="Desk_Spacer001" geometry={nodes.Desk_Spacer001.geometry} material={materials['Material.019']} />
          <mesh name="Desk_Top001" geometry={nodes.Desk_Top001.geometry} material={materials['Wood.004']} />
          <mesh name="Drawer_Bottom001" geometry={nodes.Drawer_Bottom001.geometry} material={materials['White Wood.002']} />
          <mesh name="Drawer_Top001" geometry={nodes.Drawer_Top001.geometry} material={materials['White Wood.002']} />
          <mesh name="Drawers_Back001" geometry={nodes.Drawers_Back001.geometry} material={materials['Material.020']} />
          <mesh name="Drawers_Sides001" geometry={nodes.Drawers_Sides001.geometry} material={materials['Wood.004']} />
          <mesh name="Drawers_Spacer001" geometry={nodes.Drawers_Spacer001.geometry} material={materials['White Wood.002']} />
          <mesh name="Drawers_Top001" geometry={nodes.Drawers_Top001.geometry} material={materials['Wood.004']} />
        </group>
        <group name="Laptop001" position={[0.834, 0.946, -0.098]} rotation={[0, -0.828, 0]} scale={[1.514, 1.391, 1.495]} />
        <group name="Stacked_set_of_books001" position={[0.72, 1.021, 0.813]} rotation={[0, -0.276, 0]} scale={[1.268, 1.252, 1.436]}>
          <group name="Cover_book-01001" position={[-0.001, -0.058, -0.341]} rotation={[0, -1.571, 0]}>
            <mesh name="Plane005_1" geometry={nodes.Plane005_1.geometry} material={materials['Cover book-01.001']} />
            <mesh name="Plane005_2" geometry={nodes.Plane005_2.geometry} material={materials['paper.002']} />
          </group>
          <group name="Cover_book-02001" position={[-0.001, -0.058, -0.341]} rotation={[0, -1.571, 0]}>
            <mesh name="Plane006_1" geometry={nodes.Plane006_1.geometry} material={materials['Cover book-02.001']} />
            <mesh name="Plane006_2" geometry={nodes.Plane006_2.geometry} material={materials['paper.002']} />
          </group>
          <group name="Cover_book-03001" position={[-0.001, -0.058, -0.341]} rotation={[0, -1.571, 0]}>
            <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Cover book-03.001']} />
            <mesh name="Plane007_1" geometry={nodes.Plane007_1.geometry} material={materials['paper.002']} />
          </group>
        </group>
        <group name="Salanga_Table_Lamp001" position={[0.896, 0.956, 1.121]} scale={[1.33, 1.33, 1.54]}>
          <mesh name="Black_metal001" geometry={nodes.Black_metal001.geometry} material={materials['Black metal.001']} />
          <mesh name="Bulb001" geometry={nodes.Bulb001.geometry} material={materials['Glass.001']} />
          <mesh name="Fabric001" geometry={nodes.Fabric001.geometry} material={materials['Fabric.001']} />
          <mesh name="Rattan001" geometry={nodes.Rattan001.geometry} material={materials['Rattan.001']} />
          <mesh name="White_metal001" geometry={nodes.White_metal001.geometry} material={materials['White metal.001']} />
        </group>
        <group name="Plant" position={[0.048, 0.771, 1.116]} scale={[0.158, 0.158, 0.183]}>
          <group name="Circle" scale={6.182}>
            <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Plant_Pot.001']} />
            <mesh name="Circle001_1" geometry={nodes.Circle001_1.geometry} material={materials['Plant_Soil.001']} />
          </group>
          <mesh name="IVY_Curve004" geometry={nodes.IVY_Curve004.geometry} material={materials['Plant_Stem.001']} scale={6.182} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Plant_Leaf.001']} scale={6.182} />
        </group>
        <group name="Assorted_fiction_books" position={[0.606, 0.441, 1.231]} rotation={[0, -1.408, 0]} scale={[1.659, 1.437, 1.443]}>
          <group name="Cube012" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials['Material.021']} />
            <mesh name="Cube046_1" geometry={nodes.Cube046_1.geometry} material={materials['paper.003']} />
          </group>
          <group name="Cube013" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube047" geometry={nodes.Cube047.geometry} material={materials['Material.022']} />
            <mesh name="Cube047_1" geometry={nodes.Cube047_1.geometry} material={materials['paper.003']} />
          </group>
          <group name="Cube014" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube048" geometry={nodes.Cube048.geometry} material={materials['Material.023']} />
            <mesh name="Cube048_1" geometry={nodes.Cube048_1.geometry} material={materials['paper.003']} />
          </group>
          <group name="Cube015" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube049" geometry={nodes.Cube049.geometry} material={materials['Material.024']} />
            <mesh name="Cube049_1" geometry={nodes.Cube049_1.geometry} material={materials['paper.003']} />
          </group>
          <group name="Cube016" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube050" geometry={nodes.Cube050.geometry} material={materials['Material.025']} />
            <mesh name="Cube050_1" geometry={nodes.Cube050_1.geometry} material={materials['paper.003']} />
          </group>
          <group name="Cube017" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube051" geometry={nodes.Cube051.geometry} material={materials['Material.026']} />
            <mesh name="Cube051_1" geometry={nodes.Cube051_1.geometry} material={materials['paper.003']} />
          </group>
          <group name="Cube018" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials['Material.027']} />
            <mesh name="Cube052_1" geometry={nodes.Cube052_1.geometry} material={materials['paper.003']} />
          </group>
        </group>
        <group name="Individual_Book_Collection_1" position={[0.561, 0.145, 1.228]} rotation={[0, -1.552, 0]} scale={[0.9, 0.778, 0.778]}>
          <group name="1984" position={[0, 0.127, 0.118]}>
            <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={materials['1984.001']} />
            <mesh name="Cube053_1" geometry={nodes.Cube053_1.geometry} material={materials['edge paper.001']} />
          </group>
          <group name="Book_Collectipon_01" position={[0, 0.127, 0.118]}>
            <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={materials['design.001']} />
            <mesh name="Cube054_1" geometry={nodes.Cube054_1.geometry} material={materials['edge paper.002']} />
          </group>
          <group name="factfullness" position={[0, 0.127, 0.118]}>
            <mesh name="Cube055" geometry={nodes.Cube055.geometry} material={materials['factful.001']} />
            <mesh name="Cube055_1" geometry={nodes.Cube055_1.geometry} material={materials['edge paper.002']} />
            <mesh name="Cube055_2" geometry={nodes.Cube055_2.geometry} material={materials['factful.002']} />
          </group>
          <group name="green" position={[0, 0.127, 0.118]}>
            <mesh name="Cube056" geometry={nodes.Cube056.geometry} material={materials['greenbook.001']} />
            <mesh name="Cube056_1" geometry={nodes.Cube056_1.geometry} material={materials['edge paper.003']} />
          </group>
          <group name="how_to" position={[0, 0.127, 0.118]}>
            <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials['how to.001']} />
            <mesh name="Cube057_1" geometry={nodes.Cube057_1.geometry} material={materials['edge paper.002']} />
          </group>
          <group name="hygge" position={[0, 0.127, 0.118]}>
            <mesh name="Cube058" geometry={nodes.Cube058.geometry} material={materials['hygge.001']} />
            <mesh name="Cube058_1" geometry={nodes.Cube058_1.geometry} material={materials['edge paper.004']} />
          </group>
          <group name="ikigai" position={[0, 0.127, 0.118]}>
            <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={materials['ikigai.001']} />
            <mesh name="Cube059_1" geometry={nodes.Cube059_1.geometry} material={materials['edge paper.005']} />
          </group>
          <group name="Mark_Manson" position={[0, 0.127, 0.118]}>
            <mesh name="Cube060" geometry={nodes.Cube060.geometry} material={materials['subtle.001']} />
            <mesh name="Cube060_1" geometry={nodes.Cube060_1.geometry} material={materials['edge paper.001']} />
          </group>
          <group name="sapiens" position={[0, 0.127, 0.118]}>
            <mesh name="Cube061" geometry={nodes.Cube061.geometry} material={materials['sapiens.001']} />
            <mesh name="Cube061_1" geometry={nodes.Cube061_1.geometry} material={materials['edge paper.002']} />
          </group>
        </group>
        <group name="Animated_indoor_ficus_in_a_concrete_pot" position={[-1.674, 0.07, 0.461]} scale={[1.078, 1.078, 1.249]}>
          <mesh name="ground001" geometry={nodes.ground001.geometry} material={materials['TT_checker_1024x1024_UV_GRID.003']} />
          <mesh name="plant001" geometry={nodes.plant001.geometry} material={materials['leave_1_MatSG.001']} />
          <mesh name="pot001" geometry={nodes.pot001.geometry} material={materials['Material.028']} />
        </group>
        <group name="Baroque_Window" position={[0.265, 1.314, -2.021]} rotation={[1.584, 0, 0]} scale={[1.024, 1.186, 1.024]} />
        <group name="Baroque_Window001" position={[0.264, 1.365, -2.036]} rotation={[1.595, -0.003, 0.008]} scale={[1.006, 1.165, 1.006]}>
          <mesh name="Glass" geometry={nodes.Glass.geometry} material={materials['Glass.002']} position={[0, -0.085, -0.612]} />
        </group>
        <group name="2_panel_sliding_window001" position={[0.069, 0.999, -2.056]} scale={[1.45, 1.45, 1.679]} />
        <group name="2_panel_sliding_window002" position={[0.069, 0.999, -2.056]} scale={[1.45, 1.45, 1.679]}>
          <group name="Cube002">
            <mesh name="Cube062" geometry={nodes.Cube062.geometry} material={materials['glass.001']} />
            <mesh name="Cube062_1" geometry={nodes.Cube062_1.geometry} material={materials['White Vinyl.001']} />
            <mesh name="Cube062_2" geometry={nodes.Cube062_2.geometry} material={materials['black rubber.001']} />
          </group>
          <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['glass.001']}>
            <group name="Cube001" position={[0.485, 0, 0]}>
              <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={materials['Material.029']} />
              <mesh name="Cube064_1" geometry={nodes.Cube064_1.geometry} material={materials['black rubber.001']} />
            </group>
          </mesh>
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['White Vinyl.001']}>
            <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['black rubber.001']} position={[-0.053, -0.89, 1.21]} scale={1.259} />
          </mesh>
        </group>
        <pointLight name="Point002" intensity={6} decay={2.5} distance={20} color="#fdffd6" position={[2.696, 1.923, -0.495]} rotation={[-Math.PI / 2, 0, 0]} />
        <pointLight name="Point001" intensity={6} decay={2.5} distance={20} color="#fdffd6" position={[-0.008, 2.542, -0.052]} rotation={[-Math.PI / 2, 0, 0]} />
        <pointLight name="Point" intensity={6} decay={2.5} distance={20} color="#fdffd6" position={[-0.008, 3.295, -0.052]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Wooden Floor.001']} position={[-0.007, 0.004, -0.024]} scale={[1.825, 0.637, 2.113]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.007']} position={[-0.007, -0.003, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="bookshelf002" geometry={nodes.bookshelf002.geometry} material={materials['Material.008']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="bookshelf" geometry={nodes.bookshelf.geometry} material={materials['Wood.002']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0001_Layer-3004" geometry={nodes['books-3981515_0001_Layer-3004'].geometry} material={materials['books-3981515_0001_Layer-3.002']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0001_Layer-3003" geometry={nodes['books-3981515_0001_Layer-3003'].geometry} material={materials['books-3981515_0001_Layer-3.002']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0001_Layer-3002" geometry={nodes['books-3981515_0001_Layer-3002'].geometry} material={materials['books-3981515_0001_Layer-3.002']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0001_Layer-3" geometry={nodes['books-3981515_0001_Layer-3'].geometry} material={materials['books-3981515_0001_Layer-3.002']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0000_Layer-2005" geometry={nodes['books-3981515_0000_Layer-2005'].geometry} material={materials['books-3981515_0000_Layer-2.001']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0000_Layer-2004" geometry={nodes['books-3981515_0000_Layer-2004'].geometry} material={materials['books-3981515_0000_Layer-2.001']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0000_Layer-2003" geometry={nodes['books-3981515_0000_Layer-2003'].geometry} material={materials['books-3981515_0000_Layer-2.001']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0000_Layer-2002" geometry={nodes['books-3981515_0000_Layer-2002'].geometry} material={materials['books-3981515_0000_Layer-2.001']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="polstar_2" geometry={nodes.polstar_2.geometry} material={materials['Material.015']} position={[-0.01, -0.447, 0.078]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="polstar_2001" geometry={nodes.polstar_2001.geometry} material={materials['Material.016']} position={[-0.005, -0.433, 0.05]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="Beige_Carpet001" geometry={nodes.Beige_Carpet001.geometry} material={materials['Material.018']} position={[0.013, -0.286, -0.068]} scale={[1.825, 1.825, 2.113]} />
        <group name="Office_Chair_REX" position={[-0.027, 0.099, 0.421]} rotation={[0, 0.862, 0]} scale={[1.125, 1.029, 1.101]}>
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Office Chair_Fabric.001']} />
          <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials['Office Chair_Metal.001']} />
          <mesh name="Plane010_2" geometry={nodes.Plane010_2.geometry} material={materials['Office Chair_Painted Metal.001']} />
          <mesh name="Plane010_3" geometry={nodes.Plane010_3.geometry} material={materials['Office Chair_Plastic.001']} />
        </group>
        <mesh name="Lenovo_laptop" geometry={nodes.Lenovo_laptop.geometry} material={materials['prop_laptop_lenovo_body.001']} position={[0.79, 0.949, -0.045]} rotation={[0, -0.876, 0]} scale={0.001} />
        <group name="Autumn_Picture" position={[-1.809, 1.973, -0.004]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.032, -0.891, -0.891]}>
          <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Picture_1.001']} />
          <mesh name="Plane011_1" geometry={nodes.Plane011_1.geometry} material={materials['Frame_Black.001']} />
        </group>
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.001']} position={[-0.599, 0.08, 0]} rotation={[-Math.PI, 0, 0]} scale={[1.61, 7.85, 1.64]} />
        <mesh
          geometry={nodes.About_Hitbox.geometry}
          material={nodes.About_Hitbox.material}
          visible={false}
          position={[-1.737, 1.952, 0.013]}
          scale={[0.073, 0.438, 0.613]}
          onPointerOver={() => {
            onHover("About_Hitbox", true)
            document.body.style.cursor = "pointer"
          }}
          onPointerOut={() => {
            onHover("About_Hitbox", false)
            document.body.style.cursor = "auto"
          }}
          onClick={() => {
            // openPanel("About_Hitbox")
            navigate("/about")
          }}
        />
        <mesh
          ref={aboutAnimRef}
          geometry={nodes.About_Hitbox_Anim.geometry}
          material={whiteMaterial}
          position={[-1.664, 2.39, 0.626]}
          scale={[0.009, 0.009, 0.011]}
        />
        <mesh
          geometry={nodes.Dev_Work_Hitbox.geometry}
          material={nodes.Dev_Work_Hitbox.material}
          visible={false}
          position={[0.391, 0.82, 0.497]}
          scale={[0.748, 0.693, 0.951]}
          onPointerOver={() => {
            onHover("Dev_Work_Hitbox", true)
            document.body.style.cursor = "pointer"
          }}
          onPointerOut={() => {
            onHover("Dev_Work_Hitbox", false)
            document.body.style.cursor = "auto"
          }}
          onClick={() => {
            // openPanel("Dev_Work_Hitbox")
            navigate("/dev-work")
          }}
        />
        <mesh
          ref={devWorkAnimRef}
          geometry={nodes.Dev_Work_Hitbox_Anim.geometry}
          material={whiteMaterial}
          position={[1.126, 1.5, 1.432]}
          scale={[0.018, 0.018, 0.021]}
        />
        {/* <mesh name="Dev_Work_Hitbox" geometry={nodes.Dev_Work_Hitbox.geometry} material={nodes.Dev_Work_Hitbox.material} position={[0.391, 0.82, 0.497]} scale={[0.748, 0.693, 0.951]} />
        <mesh name="Dev_Work_Hitbox_Anim" geometry={nodes.Dev_Work_Hitbox_Anim.geometry} material={nodes.Dev_Work_Hitbox_Anim.material} position={[1.126, 1.5, 1.432]} scale={[0.018, 0.018, 0.021]} />
        <mesh name="About_Hitbox" geometry={nodes.About_Hitbox.geometry} material={nodes.About_Hitbox.material} position={[-1.737, 1.952, 0.013]} scale={[0.073, 0.438, 0.613]} />
        <mesh name="About_Hitbox_Anim" geometry={nodes.About_Hitbox_Anim.geometry} material={nodes.About_Hitbox_Anim.material} position={[-1.664, 2.39, 0.626]} scale={[0.009, 0.009, 0.011]} /> */}
        <mesh name="Translucent_Curtain" geometry={nodes.Translucent_Curtain.geometry} material={materials.Cortina} position={[0.083, 2.653, -1.941]} rotation={[0, 0, 3.115]} scale={[0.253, 0.54, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/HomeOffice2_v5.glb')
