/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 models/HomeOffice5_v1.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/HomeOffice5_v1.glb')
  const { actions } = useAnimations(animations, group)
  
  React.useEffect(() => {
  Object.values(actions).forEach((action) => {
    action.reset().play()
  })
}, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Wall_corner_shelf" position={[0.121, 0.821, -0.921]} rotation={[1.571, -0.016, 1.573]} scale={0.703}>
          <mesh name="book" geometry={nodes.book.geometry} material={materials['book.012']} position={[-0.048, 0.124, -0.659]} rotation={[-Math.PI / 2, 0, -1.484]} />
          <mesh name="book001" geometry={nodes.book001.geometry} material={materials['book.013']} position={[0.005, 0.115, -0.399]} rotation={[-Math.PI / 2, -0.385, 0]} />
          <mesh name="book002" geometry={nodes.book002.geometry} material={materials['book.014']} position={[0.006, 0.109, -0.384]} rotation={[-Math.PI / 2, -0.385, 0]} />
          <mesh name="book003" geometry={nodes.book003.geometry} material={materials['book.015']} position={[-0.002, 0.109, -0.305]} rotation={[-Math.PI / 2, -0.647, 0]} />
          <mesh name="book004" geometry={nodes.book004.geometry} material={materials['book.016']} position={[0.012, 0.111, -0.365]} rotation={[-Math.PI / 2, -0.385, 0]} />
          <mesh name="book005" geometry={nodes.book005.geometry} material={materials['book.017']} position={[0.004, 0.105, -0.336]} rotation={[-Math.PI / 2, -0.821, 0]} />
          <mesh name="book006" geometry={nodes.book006.geometry} material={materials['book.018']} position={[0.008, 0.106, -0.376]} rotation={[-Math.PI / 2, -0.385, 0]} />
          <mesh name="book007" geometry={nodes.book007.geometry} material={materials['book.019']} position={[0.011, 0.104, -0.35]} rotation={[-Math.PI / 2, -1.012, 0]} />
          <mesh name="book008" geometry={nodes.book008.geometry} material={materials['book.020']} position={[-0.001, 0.1, -0.321]} rotation={[-Math.PI / 2, -0.821, 0]} />
          <mesh name="book009" geometry={nodes.book009.geometry} material={materials['book.021']} position={[-0.003, 0.1, -0.355]} rotation={[-Math.PI / 2, -0.944, 0]} />
          <mesh name="book010" geometry={nodes.book010.geometry} material={materials['book.022']} position={[-0.016, 0.119, -0.682]} rotation={[-Math.PI / 2, 0, -1.331]} />
          <mesh name="book011" geometry={nodes.book011.geometry} material={materials['book.023']} position={[-0.075, 0.126, -0.664]} rotation={[-Math.PI / 2, 0, -1.484]} />
          <mesh name="box002" geometry={nodes.box002.geometry} material={materials['box.002']} position={[0, 0.113, -0.014]} rotation={[-Math.PI / 2, 0.104, 0]}>
            <mesh name="box" geometry={nodes.box.geometry} material={materials['flowers wallpaper.001']} position={[0, 0.041, 0]} rotation={[0, -0.192, 0]}>
              <mesh name="box001" geometry={nodes.box001.geometry} material={materials['blender wallpaper.001']} position={[0, 0.048, 0]} rotation={[0, 0.051, 0]} scale={0.699} />
            </mesh>
          </mesh>
          <mesh name="casket" geometry={nodes.casket.geometry} material={materials['casket_wood.001']} position={[0.001, 0.116, -0.85]} rotation={[-1.571, 1.488, 0]} />
          <mesh name="lock" geometry={nodes.lock.geometry} material={materials['metals.001']} position={[-0.004, 0.179, -0.897]} rotation={[-1.571, 1.488, 0]} />
          <mesh name="shelf001" geometry={nodes.shelf001.geometry} material={materials['wood (Oak Matt Antracite Gray).001']} position={[0, 0.11, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="side_wall" geometry={nodes.side_wall.geometry} material={materials['wood (Oak Matt Antracite Gray).001']} position={[0.11, 0.11, -0.172]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="side_wall001" geometry={nodes.side_wall001.geometry} material={materials['wood (Oak Matt Antracite Gray).001']} position={[-0.097, 0.11, -0.172]} rotation={[Math.PI, 0, -Math.PI / 2]} />
          <mesh name="side_wall002" geometry={nodes.side_wall002.geometry} material={materials['wood (Oak Matt Antracite Gray).001']} position={[0, 0, -0.45]} rotation={[0, 0, -Math.PI]} />
          <mesh name="side_wall003" geometry={nodes.side_wall003.geometry} material={materials['wood (Oak Matt Antracite Gray).001']} position={[0, 0.207, -0.45]} rotation={[Math.PI, 0, 0]} />
          <mesh name="side_wall004" geometry={nodes.side_wall004.geometry} material={materials['wood (Oak Matt Antracite Gray).001']} position={[-0.11, 0.11, -0.729]} rotation={[0, 0, Math.PI / 2]} />
          <mesh name="side_wall005" geometry={nodes.side_wall005.geometry} material={materials['wood (Oak Matt Antracite Gray).001']} position={[0.097, 0.11, -0.729]} rotation={[Math.PI, 0, Math.PI / 2]} />
        </group>
        <group name="Empty007" position={[-0.167, 0.961, -0.931]} scale={0.738}>
          <group name="Cube067" position={[-0.033, 0.126, 0.006]} rotation={[1.573, -0.183, -1.563]} scale={0.937}>
            <mesh name="Cube105" geometry={nodes.Cube105.geometry} material={materials['book cover.004']} />
            <mesh name="Cube105_1" geometry={nodes.Cube105_1.geometry} material={materials['stacked paper.004']} />
          </group>
          <group name="Cube068" position={[-0.017, 0.128, 0.005]} rotation={[1.572, -0.181, -1.562]} scale={0.937}>
            <mesh name="Cube106_1" geometry={nodes.Cube106_1.geometry} material={materials['book cover.004']} />
            <mesh name="Cube106_2" geometry={nodes.Cube106_2.geometry} material={materials['stacked paper.004']} />
          </group>
          <group name="Cube069" position={[-0.053, 0.129, 0.007]} rotation={[1.572, -0.184, -1.563]} scale={0.937}>
            <mesh name="Cube107_1" geometry={nodes.Cube107_1.geometry} material={materials['book cover.004']} />
            <mesh name="Cube107_2" geometry={nodes.Cube107_2.geometry} material={materials['stacked paper.004']} />
          </group>
          <group name="Cube070" position={[-0.153, 0.121, 0.008]} rotation={[1.565, -0.343, -1.566]} scale={0.937}>
            <mesh name="Cube108_1" geometry={nodes.Cube108_1.geometry} material={materials['book cover.005']} />
            <mesh name="Cube108_2" geometry={nodes.Cube108_2.geometry} material={materials['stacked paper.005']} />
          </group>
          <group name="Cube071" position={[-0.135, 0.126, 0.004]} rotation={[1.574, -0.339, -1.563]} scale={0.937}>
            <mesh name="Cube109_1" geometry={nodes.Cube109_1.geometry} material={materials['book cover.004']} />
            <mesh name="Cube109_2" geometry={nodes.Cube109_2.geometry} material={materials['stacked paper.004']} />
          </group>
          <group name="Cube072" position={[-0.088, 0.11, -0.001]} rotation={[1.575, -0.323, -1.563]} scale={0.937}>
            <mesh name="Cube110_1" geometry={nodes.Cube110_1.geometry} material={materials['book cover.004']} />
            <mesh name="Cube110_2" geometry={nodes.Cube110_2.geometry} material={materials['stacked paper.004']} />
          </group>
          <group name="Cube073" position={[-0.098, 0.124, 0.004]} rotation={[1.571, -0.337, -1.564]} scale={0.937}>
            <mesh name="Cube111_1" geometry={nodes.Cube111_1.geometry} material={materials['book cover.004']} />
            <mesh name="Cube111_2" geometry={nodes.Cube111_2.geometry} material={materials['stacked paper.004']} />
          </group>
          <group name="Cube074" position={[-0.114, 0.123, 0.007]} rotation={[1.573, -0.338, -1.564]} scale={0.937}>
            <mesh name="Cube112_1" geometry={nodes.Cube112_1.geometry} material={materials['book cover.004']} />
            <mesh name="Cube112_2" geometry={nodes.Cube112_2.geometry} material={materials['stacked paper.004']} />
          </group>
          <group name="Cube075" position={[-0.176, 0.115, 0.011]} rotation={[1.573, -0.44, -1.564]} scale={0.897}>
            <mesh name="Cube113_1" geometry={nodes.Cube113_1.geometry} material={materials['book cover.004']} />
            <mesh name="Cube113_2" geometry={nodes.Cube113_2.geometry} material={materials['stacked paper.004']} />
          </group>
        </group>
        <group name="Low_Poly_Flower_Vase" position={[-0.838, 0.583, -0.198]} scale={0.183}>
          <mesh name="Vase" geometry={nodes.Vase.geometry} material={materials['Flower Vase_Color.001']} scale={1.345} />
        </group>
        <group name="Empty006" position={[-0.768, 1.202, -0.91]} scale={0.707}>
          <group name="Empty003" position={[0.244, 0, 0.01]} scale={0.297} />
          <group name="Cube106" position={[0.18, 0.097, 0.007]} rotation={[1.563, 0.425, -1.553]} scale={1.045}>
            <mesh name="Cube114_1" geometry={nodes.Cube114_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube114_2" geometry={nodes.Cube114_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube107" position={[0.389, 0.112, 0.009]} rotation={[1.562, 0.482, -1.551]} scale={1.045}>
            <mesh name="Cube115_1" geometry={nodes.Cube115_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube115_2" geometry={nodes.Cube115_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube108" position={[0.421, 0.106, 0.003]} rotation={[1.579, 0.554, -1.559]} scale={1.045}>
            <mesh name="Cube116_1" geometry={nodes.Cube116_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube116_2" geometry={nodes.Cube116_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube109" position={[0.16, 0.1, 0.005]} rotation={[1.565, 0.418, -1.557]} scale={1.045}>
            <mesh name="Cube117_1" geometry={nodes.Cube117_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube117_2" geometry={nodes.Cube117_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube110" position={[0.14, 0.088, -0.003]} rotation={[1.567, 0.372, -1.562]} scale={1.045}>
            <mesh name="Cube118_1" geometry={nodes.Cube118_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube118_2" geometry={nodes.Cube118_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube111" position={[0.362, 0.114, 0.007]} rotation={[1.558, 0.479, -1.55]} scale={1.045}>
            <mesh name="Cube119_1" geometry={nodes.Cube119_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube119_2" geometry={nodes.Cube119_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube112" position={[0.108, 0.116, -0.003]} rotation={[1.57, 0.318, -1.57]} scale={1.045}>
            <mesh name="Cube120_1" geometry={nodes.Cube120_1.geometry} material={materials['book cover.007']} />
            <mesh name="Cube120_2" geometry={nodes.Cube120_2.geometry} material={materials['stacked paper.007']} />
          </group>
          <group name="Cube113" position={[0.26, 0.111, 0.006]} rotation={[1.568, 0.439, -1.554]} scale={1.045}>
            <mesh name="Cube121_1" geometry={nodes.Cube121_1.geometry} material={materials['book cover.007']} />
            <mesh name="Cube121_2" geometry={nodes.Cube121_2.geometry} material={materials['stacked paper.007']} />
          </group>
          <group name="Cube114" position={[0.277, 0.116, -0.002]} rotation={[1.566, 0.441, -1.555]} scale={1.045}>
            <mesh name="Cube122_1" geometry={nodes.Cube122_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube122_2" geometry={nodes.Cube122_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube115" position={[0.057, 0.091, 0.008]} rotation={[1.57, 0.005, -1.573]} scale={1.045}>
            <mesh name="Cube123_1" geometry={nodes.Cube123_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube123_2" geometry={nodes.Cube123_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube116" position={[0.346, 0.098, -0.003]} rotation={[1.56, 0.461, -1.551]} scale={1.045}>
            <mesh name="Cube124_1" geometry={nodes.Cube124_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube124_2" geometry={nodes.Cube124_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube117" position={[0.322, 0.112, -0.001]} rotation={[1.565, 0.443, -1.553]} scale={1.045}>
            <mesh name="Cube125_1" geometry={nodes.Cube125_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube125_2" geometry={nodes.Cube125_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube118" position={[0.302, 0.114, 0.006]} rotation={[1.564, 0.444, -1.553]} scale={1.045}>
            <mesh name="Cube126_1" geometry={nodes.Cube126_1.geometry} material={materials['book cover.006']} />
            <mesh name="Cube126_2" geometry={nodes.Cube126_2.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube119" position={[0.099, 0.101, -0.002]} rotation={[1.572, 0.319, -1.571]} scale={1.045}>
            <mesh name="Cube127" geometry={nodes.Cube127.geometry} material={materials['book cover.006']} />
            <mesh name="Cube127_1" geometry={nodes.Cube127_1.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube120" position={[0.043, 0.1, 0.006]} rotation={[1.571, 0.003, -1.572]}>
            <mesh name="Cube128" geometry={nodes.Cube128.geometry} material={materials['book cover.006']} />
            <mesh name="Cube128_1" geometry={nodes.Cube128_1.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube121" position={[0.23, 0.109, 0.004]} rotation={[1.562, 0.431, -1.548]}>
            <mesh name="Cube129" geometry={nodes.Cube129.geometry} material={materials['book cover.006']} />
            <mesh name="Cube129_1" geometry={nodes.Cube129_1.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube122" position={[0.249, 0.108, 0.007]} rotation={[1.571, 0.439, -1.555]}>
            <mesh name="Cube130" geometry={nodes.Cube130.geometry} material={materials['book cover.006']} />
            <mesh name="Cube130_1" geometry={nodes.Cube130_1.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube123" position={[0.027, 0.1, 0.017]} rotation={[1.571, 0.003, -1.57]}>
            <mesh name="Cube131" geometry={nodes.Cube131.geometry} material={materials['book cover.006']} />
            <mesh name="Cube131_1" geometry={nodes.Cube131_1.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube124" position={[0.008, 0.087, 0.014]} rotation={[1.571, 0.003, -1.57]}>
            <mesh name="Cube132" geometry={nodes.Cube132.geometry} material={materials['book cover.006']} />
            <mesh name="Cube132_1" geometry={nodes.Cube132_1.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube125" position={[0.206, 0.111, 0.001]} rotation={[1.563, 0.432, -1.552]}>
            <mesh name="Cube133" geometry={nodes.Cube133.geometry} material={materials['book cover.006']} />
            <mesh name="Cube133_1" geometry={nodes.Cube133_1.geometry} material={materials['stacked paper.006']} />
          </group>
          <group name="Cube126" position={[0.191, 0.107, 0.003]} rotation={[1.562, 0.429, -1.549]}>
            <mesh name="Cube134" geometry={nodes.Cube134.geometry} material={materials['book cover.007']} />
            <mesh name="Cube134_1" geometry={nodes.Cube134_1.geometry} material={materials['stacked paper.007']} />
          </group>
        </group>
        <group name="IMac_computer" position={[-0.433, 0.672, -0.813]} rotation={[0, -0.033, 0]} scale={0.587}>
          <group name="Apple_iMac" rotation={[0, -1.554, 0]}>
            <mesh name="Untitled001" geometry={nodes.Untitled001.geometry} material={materials['aluminium.001']} />
            <mesh name="Untitled001_1" geometry={nodes.Untitled001_1.geometry} material={materials['rubber.001']} />
            <mesh name="Untitled001_2" geometry={nodes.Untitled001_2.geometry} material={materials['black plastic.001']} />
            <mesh name="Untitled001_3" geometry={nodes.Untitled001_3.geometry} material={materials['glass.002']} />
            <mesh name="Untitled001_4" geometry={nodes.Untitled001_4.geometry} material={materials['glass frame.001']} />
            <mesh name="Untitled001_5" geometry={nodes.Untitled001_5.geometry} material={materials['display frame.001']} />
            <mesh name="Untitled001_6" geometry={nodes.Untitled001_6.geometry} material={materials['display.001']} />
            <mesh name="Untitled001_7" geometry={nodes.Untitled001_7.geometry} material={materials['white plastic.001']} />
            <mesh name="Untitled001_8" geometry={nodes.Untitled001_8.geometry} material={materials['metal.003']} />
            <mesh name="Untitled001_9" geometry={nodes.Untitled001_9.geometry} material={materials['yellow metal.001']} />
            <mesh name="Untitled001_10" geometry={nodes.Untitled001_10.geometry} material={materials['camera.001']} />
            <mesh name="Untitled001_11" geometry={nodes.Untitled001_11.geometry} material={materials['keys left.001']} />
            <mesh name="Untitled001_12" geometry={nodes.Untitled001_12.geometry} material={materials['glossy white plastic.001']} />
            <mesh name="Untitled001_13" geometry={nodes.Untitled001_13.geometry} material={materials['matt white plastic.001']} />
            <mesh name="Untitled001_14" geometry={nodes.Untitled001_14.geometry} material={materials['rubber.002']} />
            <mesh name="Untitled001_15" geometry={nodes.Untitled001_15.geometry} material={materials['plastic black.001']} />
            <mesh name="Untitled001_16" geometry={nodes.Untitled001_16.geometry} material={materials['plastic green.001']} />
            <mesh name="Untitled001_17" geometry={nodes.Untitled001_17.geometry} material={materials['switch top.001']} />
            <mesh name="Untitled001_18" geometry={nodes.Untitled001_18.geometry} material={materials['chrome.001']} />
            <mesh name="Untitled001_19" geometry={nodes.Untitled001_19.geometry} material={materials['plastic top.001']} />
          </group>
        </group>
        <group name="Table_Lamp" position={[-0.797, 0.692, -0.715]} scale={0.383}>
          <mesh name="Bulb" geometry={nodes.Bulb.geometry} material={materials['Bulb.001']} position={[0, 0.568, 0]} />
          <group name="Lamp_Body">
            <mesh name="Cylinder014" geometry={nodes.Cylinder014.geometry} material={materials['Metal_Base.001']} />
            <mesh name="Cylinder014_1" geometry={nodes.Cylinder014_1.geometry} material={materials['Material.032']} />
          </group>
          <mesh name="Lamp_Cover" geometry={nodes.Lamp_Cover.geometry} material={materials['Lamp Cover.001']} position={[0, 0.51, 0]} scale={[1.1, 1, 1.1]} />
          <mesh name="Wire" geometry={nodes.Wire.geometry} material={materials['Wire.001']} position={[0.012, 0, 0.029]} rotation={[-Math.PI, 1.178, -Math.PI]} scale={0.9} />
        </group>
        <group name="Modular_plant" position={[-0.018, 0.669, -0.798]} scale={0.088}>
          <group name="Empty001" position={[-0.035, 0.092, 0.039]} rotation={[0, 1.323, 0]} scale={0.557} />
          <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Ceramic Glazed.001']} position={[-0.035, 0.91, 0.039]} scale={0.588} />
          <mesh name="FEUILLE001" geometry={nodes.FEUILLE001.geometry} material={materials['Material.033']} position={[-0.035, 0.039, 0.039]} scale={0.588} />
          <mesh name="pebble545" geometry={nodes.pebble545.geometry} material={materials['rock wall.001']} position={[-0.05, 0.851, 0.027]} rotation={[2.858, -1.017, 0.183]} scale={0.588} />
        </group>
        <group name="Bookcase_01" position={[-0.836, 0.211, 0.51]} rotation={[0, 1.562, 0]} scale={0.569}>
          <group name="BOOK1" scale={0.207}>
            <mesh name="Plane037" geometry={nodes.Plane037.geometry} material={materials['GREY.001']} />
            <mesh name="Plane037_1" geometry={nodes.Plane037_1.geometry} material={materials['BLACK-PLASTIC.001']} />
            <mesh name="Plane037_2" geometry={nodes.Plane037_2.geometry} material={materials['WHITE.001']} />
            <group name="BOOK2" scale={4.825}>
              <mesh name="Plane038" geometry={nodes.Plane038.geometry} material={materials['MAROON.001']} />
              <mesh name="Plane038_1" geometry={nodes.Plane038_1.geometry} material={materials['GOLD.001']} />
              <mesh name="Plane038_2" geometry={nodes.Plane038_2.geometry} material={materials['WHITE.001']} />
            </group>
            <group name="BOOK3" scale={4.825}>
              <mesh name="Plane039" geometry={nodes.Plane039.geometry} material={materials['CREAM.001']} />
              <mesh name="Plane039_1" geometry={nodes.Plane039_1.geometry} material={materials['WHITE.001']} />
            </group>
            <group name="BOOK4" scale={4.825}>
              <mesh name="Plane040" geometry={nodes.Plane040.geometry} material={materials['BLACK-PLASTIC.001']} />
              <mesh name="Plane040_1" geometry={nodes.Plane040_1.geometry} material={materials['WHITE.001']} />
            </group>
            <group name="BOOK5" scale={4.825}>
              <mesh name="Plane041" geometry={nodes.Plane041.geometry} material={materials['LIME.001']} />
              <mesh name="Plane041_1" geometry={nodes.Plane041_1.geometry} material={materials['RED.001']} />
              <mesh name="Plane041_2" geometry={nodes.Plane041_2.geometry} material={materials['WHITE.001']} />
            </group>
          </group>
          <group name="BOOKSET" scale={0.207}>
            <mesh name="Plane042" geometry={nodes.Plane042.geometry} material={materials['GREY.001']} />
            <mesh name="Plane042_1" geometry={nodes.Plane042_1.geometry} material={materials['BLACK-PLASTIC.001']} />
            <mesh name="Plane042_2" geometry={nodes.Plane042_2.geometry} material={materials['WHITE.001']} />
          </group>
          <mesh name="BOOKSHELF01" geometry={nodes.BOOKSHELF01.geometry} material={materials['CREAM-WOOD-TEXTURE.001']} scale={0.207}>
            <mesh name="TRANSPARENT-GLASS" geometry={nodes['TRANSPARENT-GLASS'].geometry} material={materials['GLASS.001']} position={[-1.125, 3.403, 0]} rotation={[0, 0, -Math.PI / 2]} scale={1.024} />
            <mesh name="TRANSPARENT-GLASS-FRAME" geometry={nodes['TRANSPARENT-GLASS-FRAME'].geometry} material={materials['BLACK-PLASTIC.001']} position={[-1.127, 3.402, 0]} rotation={[0, 0, -Math.PI / 2]} />
          </mesh>
          <group name="CANDLE01" scale={0.207}>
            <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials['CYAN.001']} />
            <mesh name="Cylinder016_1" geometry={nodes.Cylinder016_1.geometry} material={materials['BLACK-PLASTIC.001']} />
          </group>
          <group name="CANDLE02" scale={0.207}>
            <mesh name="Cylinder017" geometry={nodes.Cylinder017.geometry} material={materials['CYAN.001']} />
            <mesh name="Cylinder017_1" geometry={nodes.Cylinder017_1.geometry} material={materials['BLACK-PLASTIC.001']} />
          </group>
          <group name="CHEST" scale={0.207}>
            <mesh name="Cube136" geometry={nodes.Cube136.geometry} material={materials['RED.001']} />
            <mesh name="Cube136_1" geometry={nodes.Cube136_1.geometry} material={materials['GOLD.001']} />
            <group name="CHEST-CAP" scale={4.825}>
              <mesh name="Cube137" geometry={nodes.Cube137.geometry} material={materials['GOLD.001']} />
              <mesh name="Cube137_1" geometry={nodes.Cube137_1.geometry} material={materials['RED.001']} />
            </group>
            <mesh name="CHEST-LEATHER" geometry={nodes['CHEST-LEATHER'].geometry} material={materials['RED.001']} scale={4.825} />
          </group>
          <mesh name="CONTAINER01" geometry={nodes.CONTAINER01.geometry} material={materials['WHITE.001']} scale={0.207}>
            <mesh name="CAPE01" geometry={nodes.CAPE01.geometry} material={materials['GOLD.001']} scale={4.825} />
          </mesh>
          <mesh name="CONTAINER02" geometry={nodes.CONTAINER02.geometry} material={materials['WHITE.001']} scale={0.207}>
            <mesh name="CAPE02" geometry={nodes.CAPE02.geometry} material={materials['GOLD.001']} scale={4.825} />
          </mesh>
          <mesh name="DECORATION" geometry={nodes.DECORATION.geometry} material={materials['GOLD.001']} scale={0.207} />
          <mesh name="FRAME01" geometry={nodes.FRAME01.geometry} material={materials['BLACK-PLASTIC.001']} scale={0.207}>
            <mesh name="PHOTO01" geometry={nodes.PHOTO01.geometry} material={materials['PHOTO01.001']} scale={4.825} />
          </mesh>
          <mesh name="FRAME02" geometry={nodes.FRAME02.geometry} material={materials['BLACK-PLASTIC.001']} scale={0.207}>
            <mesh name="PHOTO02" geometry={nodes.PHOTO02.geometry} material={materials['PHOTO02.001']} scale={4.825} />
          </mesh>
          <mesh name="LAMP" geometry={nodes.LAMP.geometry} material={materials['SILVER.001']} scale={0.207}>
            <mesh name="BULB" geometry={nodes.BULB.geometry} material={materials['LED.001']} scale={4.825} />
            <mesh name="CASING" geometry={nodes.CASING.geometry} material={materials['GOLD.001']} scale={4.825} />
            <mesh name="POLE" geometry={nodes.POLE.geometry} material={materials['SILVER.001']} scale={4.825} />
          </mesh>
          <group name="RUBIC-CUBE" scale={0.207}>
            <mesh name="Cube139" geometry={nodes.Cube139.geometry} material={materials['WHITE.001']} />
            <mesh name="Cube139_1" geometry={nodes.Cube139_1.geometry} material={materials['RED.001']} />
            <mesh name="Cube139_2" geometry={nodes.Cube139_2.geometry} material={materials['YELLOW.001']} />
            <mesh name="Cube139_3" geometry={nodes.Cube139_3.geometry} material={materials['LIME.001']} />
            <mesh name="Cube139_4" geometry={nodes.Cube139_4.geometry} material={materials['BLUE.001']} />
            <mesh name="Cube139_5" geometry={nodes.Cube139_5.geometry} material={materials['ORANGE.001']} />
            <mesh name="Cube139_6" geometry={nodes.Cube139_6.geometry} material={materials['PURPLE.001']} />
          </group>
        </group>
        <group name="Brown_and_beige_Rug001" position={[0.279, 0.262, 0.142]} scale={[0.188, 0.188, 0.161]}>
          <group name="Curves_32" position={[0, 0.005, 0]} />
          <mesh name="Tapis_32" geometry={nodes.Tapis_32.geometry} material={materials['tapis 32.001']} position={[0, -0.29, 0]} scale={3.024} />
        </group>
        <group name="Marble_Round_Table" position={[0.382, 0.217, 0.126]} scale={0.356}>
          <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['American Oak.001']} scale={[0.499, 0.622, 0.499]} />
          <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['American Oak.001']} position={[0, 0.711, 0]} scale={[0.499, 0.622, 0.499]} />
          <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={materials['Carrara Marble.001']} position={[0, 0.768, 0]} scale={0.906} />
          <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['American Oak.001']} position={[0, 0.03, 0]} rotation={[Math.PI, -0.175, Math.PI]} scale={[0.621, 0.774, 0.556]} />
        </group>
        <group name="Plant001" position={[0.566, 0.209, -0.746]} scale={0.517}>
          <mesh name="PlantMonstera" geometry={nodes.PlantMonstera.geometry} material={materials['Plant.001']} scale={0.736} />
          <mesh name="Clay" geometry={nodes.Clay.geometry} material={materials['BrownClay.001']} />
          <mesh name="Vase001" geometry={nodes.Vase001.geometry} material={materials['Clay Gray.001']} />
        </group>
        <group name="Back-Wing_Chair" position={[-0.386, 0.225, -0.608]} rotation={[0, -0.063, 0]}>
          <mesh name="560_BACK-WING_CHAIR_BackLegs" geometry={nodes['560_BACK-WING_CHAIR_BackLegs'].geometry} material={materials['beech wood.002']} rotation={[Math.PI, -0.045, Math.PI]} scale={0.648}>
            <mesh name="560_BACK-WING_CHAIR_Bushes001" geometry={nodes['560_BACK-WING_CHAIR_Bushes001'].geometry} material={materials['BackWingChairBushes.002']} />
            <mesh name="560_BACK-WING_CHAIR_Seat001" geometry={nodes['560_BACK-WING_CHAIR_Seat001'].geometry} material={materials['BackWingChairLeather.002']}>
              <mesh name="560_BACK-WING_CHAIR_SeatWire001" geometry={nodes['560_BACK-WING_CHAIR_SeatWire001'].geometry} material={materials['BackWingChairLeather.002']} />
            </mesh>
            <mesh name="560_BACK-WING_CHAIR_Support001" geometry={nodes['560_BACK-WING_CHAIR_Support001'].geometry} material={materials['beech wood.002']} />
            <mesh name="560_BACK-WING_CHAIR_BackWing001" geometry={nodes['560_BACK-WING_CHAIR_BackWing001'].geometry} material={materials['BackWingChairLeather.002']}>
              <mesh name="560_BACK-WING_CHAIR_BackWingWire001" geometry={nodes['560_BACK-WING_CHAIR_BackWingWire001'].geometry} material={materials['BackWingChairLeather.002']} />
            </mesh>
          </mesh>
          <mesh name="560_BACK-WING_CHAIR_FrontLegs" geometry={nodes['560_BACK-WING_CHAIR_FrontLegs'].geometry} material={materials['beech wood.002']} rotation={[Math.PI, -0.045, Math.PI]} scale={0.648} />
        </group>
        <pointLight intensity={4} decay={2.5} distance={15}color="#ffeecd" position={[-0.008, 1.48, -0.051]} rotation={[-Math.PI / 2, 0, 0]} scale={[-7.693, -9.887, -19.1]} />
        <pointLight intensity={2} decay={2.5} distance={15}color="#ffeecd" position={[-0.008, 3.48, -0.051]} rotation={[-Math.PI / 2, 0, 0]} scale={[-7.693, -9.887, -19.1]} />
        <mesh name="Globe_inner_pin001" geometry={nodes.Globe_inner_pin001.geometry} material={materials.stainless} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Beige Marble floor.001']} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.030']} position={[0, 1.004, 0]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.036']} position={[0.011, 0.01, -0.011]} scale={[7.748, 8.557, 7.748]} />
        <group name="Corner_desk" position={[-0.408, 0.201, -0.507]} rotation={[0, 1.562, 0]} scale={[0.64, 0.64, 0.792]}>
          <mesh name="Cube095" geometry={nodes.Cube095.geometry} material={materials['wood.002']} />
          <mesh name="Cube095_1" geometry={nodes.Cube095_1.geometry} material={materials['white paint.002']} />
          <mesh name="Cube095_2" geometry={nodes.Cube095_2.geometry} material={materials['metal.002']} />
          <group name="Cube006" position={[0.118, 0.399, -0.503]} rotation={[0, 0.14, 0]}>
            <mesh name="Cube096" geometry={nodes.Cube096.geometry} material={materials['cover.002']} />
            <mesh name="Cube096_1" geometry={nodes.Cube096_1.geometry} material={materials['pages.002']} />
          </group>
          <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['white paint.002']} position={[-0.122, 0.041, -0.548]} rotation={[0, -1.571, 0]} scale={[0.137, 0.102, 0.137]}>
            <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Woven Rattan Pattern.002']} />
          </mesh>
          <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['white paint.002']} position={[0.104, 0.041, -0.534]} rotation={[Math.PI, -1.553, Math.PI]} scale={[0.137, 0.102, 0.137]}>
            <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Woven Rattan Pattern.002']} />
          </mesh>
          <group name="Plane008" position={[-0.103, 0.604, -0.532]} rotation={[0, 0.042, 0]}>
            <mesh name="Plane032" geometry={nodes.Plane032.geometry} material={materials['Metal wire mesh.002']} />
            <mesh name="Plane032_1" geometry={nodes.Plane032_1.geometry} material={materials['metal.002']} />
            <group name="Plane003" position={[-0.001, 0.032, 0]} rotation={[Math.PI, 0, Math.PI]} scale={[0.149, 1, 0.105]}>
              <mesh name="Plane033" geometry={nodes.Plane033.geometry} material={materials['pages.002']} />
              <mesh name="Plane033_1" geometry={nodes.Plane033_1.geometry} material={materials['Material.031']} />
            </group>
            <group name="Plane010" position={[0.002, 0.028, 0]}>
              <mesh name="Plane034" geometry={nodes.Plane034.geometry} material={materials['pages.002']} />
              <mesh name="Plane034_1" geometry={nodes.Plane034_1.geometry} material={materials['color.002']} />
              <mesh name="Plane034_2" geometry={nodes.Plane034_2.geometry} material={nodes.Plane034_2.material} />
              <mesh name="Plane034_3" geometry={nodes.Plane034_3.geometry} material={materials['metal.002']} />
            </group>
          </group>
          <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['cover.002']} position={[-0.681, 0.008, -0.371]} scale={0.026} />
          <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['metal.002']} position={[-0.076, 0.399, -0.461]} scale={0.051} />
        </group>
        <mesh name="Hanging_shelf" geometry={nodes.Hanging_shelf.geometry} material={materials['Desk wood.002']} position={[-0.484, 1.181, -0.992]} rotation={[1.533, 0, 0]} scale={[0.981, 0.736, 0.818]} />
        <mesh name="Old_ceramic_vase" geometry={nodes.Old_ceramic_vase.geometry} material={materials['marble (cracked).001']} position={[-0.468, 0.97, -0.911]} />
        <mesh name="Picture_frame002" geometry={nodes.Picture_frame002.geometry} material={materials['Material.034']} position={[-0.991, 1.194, -0.311]} rotation={[1.57, -0.008, -1.538]} scale={0.826} />
        <mesh name="Circular_Leather_Pillow" geometry={nodes.Circular_Leather_Pillow.geometry} material={materials['Material.035']} position={[0.401, 0.215, 0.462]} />
        <mesh name="Globe_-_Blue_White" geometry={nodes['Globe_-_Blue_White'].geometry} material={materials['globe texture.001']} position={[0.422, 0.498, 0.151]}>
          <mesh name="Globe_holder" geometry={nodes.Globe_holder.geometry} material={materials['stainless.001']} rotation={[Math.PI / 2, -0.549, -Math.PI]} />
          <mesh name="Globe_inner_pin" geometry={nodes.Globe_inner_pin.geometry} material={materials['stainless.001']} rotation={[0, 0, -0.549]} />
          <mesh name="Globe_inner_pin002" geometry={nodes.Globe_inner_pin002.geometry} material={materials['stainless.001']} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="Globe_inner_pin003" geometry={nodes.Globe_inner_pin003.geometry} material={materials['stainless.001']} rotation={[0, 0, -Math.PI / 2]} />
          <mesh name="outer_holder" geometry={nodes.outer_holder.geometry} material={materials['stainless.001']} rotation={[Math.PI / 2, 0, 0]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/HomeOffice5_v1.glb')
