/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HomeOffice2_v4.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'
import { gsap } from 'gsap'
import { useNavigate } from 'react-router'

export default function Model(props) {
  let navigate = useNavigate()

  const { nodes, materials, animations } = useGLTF('/models/HomeOffice2_v4.glb')
  const group = React.useRef()
  const whiteMaterial = new THREE.MeshBasicMaterial({ color: 0xffffff})

  const aboutAnimRef = useRef()
  const devWorkAnimRef = useRef()
  const animationPairs = {
    About_Hitbox: { ref: aboutAnimRef },
    Dev_Work_Hitbox: { ref: devWorkAnimRef },
    
  }
  const originalScales = {
    About_Hitbox: { x: 0.009, y: 0.009, z: 0.011 },
    Dev_Work_Hitbox: {x: 0.018, y: 0.018, z: 0.021 }
  };
  // Handle Hover
  const onHover = (key, isHovering) => {
    const animObject = animationPairs[key]
  // Như này to quá
  //   gsap.to(animObject.ref.current.scale, {
  //     x: isHovering ? 1 : 0,
  //     y: isHovering ? 1 : 0,
  //     z: isHovering ? 1 : 0, 
  //     duration: 0.8,
  // })
    const base = originalScales[key];
    gsap.to(animObject.ref.current.scale, {
      x: isHovering ? base.x : 0,
      y: isHovering ? base.y : 0,
      z: isHovering ? base.z : 0,
      duration: 0.9,
      ease: "power1.out"
    });
  }
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
  Object.values(actions).forEach((action) => {
    action.reset().play()
  })
}, [actions]) 
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Salanga_Table_Lamp" position={[0.896, 0.956, 1.121]} scale={[1.33, 1.33, 1.54]} />
        <group name="Stacked_set_of_books" position={[0.72, 1.021, 0.813]} rotation={[0, -0.276, 0]} scale={[1.268, 1.252, 1.436]} />
        <group name="2_panel_sliding_window" position={[0.069, 0.999, -2.056]} scale={[1.45, 1.45, 1.679]} />
        <group name="Floating_shelf_with_decoration" position={[-1.831, 1.669, 1.015]} rotation={[1.58, 0.011, -1.493]} scale={[2.112, 1.827, 1.825]}>
          <group name="Cube007" position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Cube098" geometry={nodes.Cube098.geometry} material={materials['Material.051']} />
            <mesh name="Cube098_1" geometry={nodes.Cube098_1.geometry} material={materials['paper.007']} />
          </group>
          <group name="Cube008" position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Cube099" geometry={nodes.Cube099.geometry} material={materials['Material.052']} />
            <mesh name="Cube099_1" geometry={nodes.Cube099_1.geometry} material={materials['paper.007']} />
          </group>
          <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Ground.003']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Ceramica off white.003']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Vidro colorido.003']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <group name="Cylinder001" position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Mesh014" geometry={nodes.Mesh014.geometry} material={materials['Candle Wax.003']} />
            <mesh name="Mesh014_1" geometry={nodes.Mesh014_1.geometry} material={materials['Rope.003']} />
          </group>
          <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Vidro.003']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <group name="Cylinder007" position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Mesh016" geometry={nodes.Mesh016.geometry} material={materials['Wood.008']} />
            <mesh name="Mesh016_1" geometry={nodes.Mesh016_1.geometry} material={materials['Material.053']} />
          </group>
          <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials['Vidro colorido.003']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="Plane025" geometry={nodes.Plane025.geometry} material={materials['Material.054']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh name="shelf" geometry={nodes.shelf.geometry} material={materials['laqueado brilhoso branco.003']} position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="Likestone_Sofa" position={[0.132, 0.092, -1.54]} scale={[1.045, 1.045, 1.21]}>
          <mesh name="Buttons" geometry={nodes.Buttons.geometry} material={materials['Material.055']} position={[0, -0.001, 0]} />
          <mesh name="Sofa_frame" geometry={nodes.Sofa_frame.geometry} material={materials['Material.056']} position={[0.018, -0.12, 0.032]} />
        </group>
        <group name="Belfield_L-Shape_Desk" position={[0.361, 0.128, 0.751]} rotation={[0, -1.551, 0]} scale={[1.243, 1.074, 1.074]}>
          <mesh name="Desk_Side" geometry={nodes.Desk_Side.geometry} material={materials['Wood Parquet.003']} />
          <mesh name="Desk_Spacer" geometry={nodes.Desk_Spacer.geometry} material={materials['Wood Parquet.003']} />
          <mesh name="Desk_Top" geometry={nodes.Desk_Top.geometry} material={materials['Wood dark.003']} />
          <mesh name="Drawer_Bottom" geometry={nodes.Drawer_Bottom.geometry} material={materials['White Wood.005']} />
          <mesh name="Drawer_Top" geometry={nodes.Drawer_Top.geometry} material={materials['Wood Parquet.003']} />
          <mesh name="Drawers_Back" geometry={nodes.Drawers_Back.geometry} material={materials['Wood Parquet.003']} />
          <mesh name="Drawers_Sides" geometry={nodes.Drawers_Sides.geometry} material={materials['Wood dark.003']} />
          <mesh name="Drawers_Spacer" geometry={nodes.Drawers_Spacer.geometry} material={materials['Material.059']} />
          <mesh name="Drawers_Top" geometry={nodes.Drawers_Top.geometry} material={materials['Wood Parquet.003']} />
        </group>
        <group name="Belfield_L-Shape_Desk001" position={[0.361, 0.128, 0.751]} rotation={[0, -1.551, 0]} scale={[1.243, 1.074, 1.074]}>
          <mesh name="Desk_Side001" geometry={nodes.Desk_Side001.geometry} material={materials['Wood Parquet.003']} />
          <mesh name="Desk_Spacer001" geometry={nodes.Desk_Spacer001.geometry} material={materials['Material.061']} />
          <mesh name="Desk_Top001" geometry={nodes.Desk_Top001.geometry} material={materials['Wood.009']} />
          <mesh name="Drawer_Bottom001" geometry={nodes.Drawer_Bottom001.geometry} material={materials['White Wood.006']} />
          <mesh name="Drawer_Top001" geometry={nodes.Drawer_Top001.geometry} material={materials['White Wood.006']} />
          <mesh name="Drawers_Back001" geometry={nodes.Drawers_Back001.geometry} material={materials['Material.062']} />
          <mesh name="Drawers_Sides001" geometry={nodes.Drawers_Sides001.geometry} material={materials['Wood.009']} />
          <mesh name="Drawers_Spacer001" geometry={nodes.Drawers_Spacer001.geometry} material={materials['White Wood.006']} />
          <mesh name="Drawers_Top001" geometry={nodes.Drawers_Top001.geometry} material={materials['Wood.009']} />
        </group>
        <group name="Laptop001" position={[0.834, 0.946, -0.098]} rotation={[0, -0.828, 0]} scale={[1.514, 1.391, 1.495]} />
        <group name="Stacked_set_of_books001" position={[0.72, 1.021, 0.813]} rotation={[0, -0.276, 0]} scale={[1.268, 1.252, 1.436]}>
          <group name="Cover_book-01001" position={[-0.001, -0.058, -0.341]} rotation={[0, -1.571, 0]}>
            <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials['Cover book-01.003']} />
            <mesh name="Plane022_1" geometry={nodes.Plane022_1.geometry} material={materials['paper.008']} />
          </group>
          <group name="Cover_book-02001" position={[-0.001, -0.058, -0.341]} rotation={[0, -1.571, 0]}>
            <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials['Cover book-02.003']} />
            <mesh name="Plane023_1" geometry={nodes.Plane023_1.geometry} material={materials['paper.008']} />
          </group>
          <group name="Cover_book-03001" position={[-0.001, -0.058, -0.341]} rotation={[0, -1.571, 0]}>
            <mesh name="Plane024" geometry={nodes.Plane024.geometry} material={materials['Cover book-03.003']} />
            <mesh name="Plane024_1" geometry={nodes.Plane024_1.geometry} material={materials['paper.008']} />
          </group>
        </group>
        <group name="Salanga_Table_Lamp001" position={[0.896, 0.956, 1.121]} scale={[1.33, 1.33, 1.54]}>
          <mesh name="Black_metal001" geometry={nodes.Black_metal001.geometry} material={materials['Black metal.003']} />
          <mesh name="Bulb001" geometry={nodes.Bulb001.geometry} material={materials['Glass.005']} />
          <mesh name="Fabric001" geometry={nodes.Fabric001.geometry} material={materials['Fabric.003']} />
          <mesh name="Rattan001" geometry={nodes.Rattan001.geometry} material={materials['Rattan.003']} />
          <mesh name="White_metal001" geometry={nodes.White_metal001.geometry} material={materials['White metal.003']} />
        </group>
        <group name="Plant" position={[0.048, 0.771, 1.116]} scale={[0.158, 0.158, 0.183]}>
          <group name="Circle" scale={6.182}>
            <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Plant_Pot.003']} />
            <mesh name="Circle003_1" geometry={nodes.Circle003_1.geometry} material={materials['Plant_Soil.003']} />
          </group>
          <mesh name="IVY_Curve004" geometry={nodes.IVY_Curve004.geometry} material={materials['Plant_Stem.003']} scale={6.182} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Plant_Leaf.003']} scale={6.182} />
        </group>
        <group name="Assorted_fiction_books" position={[0.606, 0.441, 1.231]} rotation={[0, -1.408, 0]} scale={[1.659, 1.437, 1.443]}>
          <group name="Cube012" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube120" geometry={nodes.Cube120.geometry} material={materials['Material.063']} />
            <mesh name="Cube120_1" geometry={nodes.Cube120_1.geometry} material={materials['paper.009']} />
          </group>
          <group name="Cube013" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube121" geometry={nodes.Cube121.geometry} material={materials['Material.064']} />
            <mesh name="Cube121_1" geometry={nodes.Cube121_1.geometry} material={materials['paper.009']} />
          </group>
          <group name="Cube014" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube122" geometry={nodes.Cube122.geometry} material={materials['Material.065']} />
            <mesh name="Cube122_1" geometry={nodes.Cube122_1.geometry} material={materials['paper.009']} />
          </group>
          <group name="Cube015" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube123" geometry={nodes.Cube123.geometry} material={materials['Material.066']} />
            <mesh name="Cube123_1" geometry={nodes.Cube123_1.geometry} material={materials['paper.009']} />
          </group>
          <group name="Cube016" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube124" geometry={nodes.Cube124.geometry} material={materials['Material.067']} />
            <mesh name="Cube124_1" geometry={nodes.Cube124_1.geometry} material={materials['paper.009']} />
          </group>
          <group name="Cube017" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube125" geometry={nodes.Cube125.geometry} material={materials['Material.068']} />
            <mesh name="Cube125_1" geometry={nodes.Cube125_1.geometry} material={materials['paper.009']} />
          </group>
          <group name="Cube018" position={[-0.727, -0.997, 0.413]}>
            <mesh name="Cube126" geometry={nodes.Cube126.geometry} material={materials['Material.069']} />
            <mesh name="Cube126_1" geometry={nodes.Cube126_1.geometry} material={materials['paper.009']} />
          </group>
        </group>
        <group name="Individual_Book_Collection_1" position={[0.561, 0.145, 1.228]} rotation={[0, -1.552, 0]} scale={[0.9, 0.778, 0.778]}>
          <group name="1984" position={[0, 0.127, 0.118]}>
            <mesh name="Cube127" geometry={nodes.Cube127.geometry} material={materials['1984.003']} />
            <mesh name="Cube127_1" geometry={nodes.Cube127_1.geometry} material={materials['edge paper.011']} />
          </group>
          <group name="Book_Collectipon_01" position={[0, 0.127, 0.118]}>
            <mesh name="Cube128" geometry={nodes.Cube128.geometry} material={materials['design.003']} />
            <mesh name="Cube128_1" geometry={nodes.Cube128_1.geometry} material={materials['edge paper.012']} />
          </group>
          <group name="factfullness" position={[0, 0.127, 0.118]}>
            <mesh name="Cube129" geometry={nodes.Cube129.geometry} material={materials['factful.005']} />
            <mesh name="Cube129_1" geometry={nodes.Cube129_1.geometry} material={materials['edge paper.012']} />
            <mesh name="Cube129_2" geometry={nodes.Cube129_2.geometry} material={materials['factful.006']} />
          </group>
          <group name="green" position={[0, 0.127, 0.118]}>
            <mesh name="Cube130" geometry={nodes.Cube130.geometry} material={materials['greenbook.003']} />
            <mesh name="Cube130_1" geometry={nodes.Cube130_1.geometry} material={materials['edge paper.013']} />
          </group>
          <group name="how_to" position={[0, 0.127, 0.118]}>
            <mesh name="Cube131" geometry={nodes.Cube131.geometry} material={materials['how to.003']} />
            <mesh name="Cube131_1" geometry={nodes.Cube131_1.geometry} material={materials['edge paper.012']} />
          </group>
          <group name="hygge" position={[0, 0.127, 0.118]}>
            <mesh name="Cube132" geometry={nodes.Cube132.geometry} material={materials['hygge.003']} />
            <mesh name="Cube132_1" geometry={nodes.Cube132_1.geometry} material={materials['edge paper.014']} />
          </group>
          <group name="ikigai" position={[0, 0.127, 0.118]}>
            <mesh name="Cube133" geometry={nodes.Cube133.geometry} material={materials['ikigai.003']} />
            <mesh name="Cube133_1" geometry={nodes.Cube133_1.geometry} material={materials['edge paper.015']} />
          </group>
          <group name="Mark_Manson" position={[0, 0.127, 0.118]}>
            <mesh name="Cube134" geometry={nodes.Cube134.geometry} material={materials['subtle.003']} />
            <mesh name="Cube134_1" geometry={nodes.Cube134_1.geometry} material={materials['edge paper.011']} />
          </group>
          <group name="sapiens" position={[0, 0.127, 0.118]}>
            <mesh name="Cube135" geometry={nodes.Cube135.geometry} material={materials['sapiens.003']} />
            <mesh name="Cube135_1" geometry={nodes.Cube135_1.geometry} material={materials['edge paper.012']} />
          </group>
        </group>
        <group name="Animated_indoor_ficus_in_a_concrete_pot" position={[-1.674, 0.07, 0.461]} scale={[1.078, 1.078, 1.249]}>
          <mesh name="ground001" geometry={nodes.ground001.geometry} material={materials['TT_checker_1024x1024_UV_GRID.002']} />
          <mesh name="plant001" geometry={nodes.plant001.geometry} material={materials['leave_1_MatSG.003']} />
          <mesh name="pot001" geometry={nodes.pot001.geometry} material={materials['Material.070']} />
        </group>
        <group name="Baroque_Window" position={[0.265, 1.314, -2.021]} rotation={[1.584, 0, 0]} scale={[1.024, 1.186, 1.024]} />
        <group name="Baroque_Window001" position={[0.264, 1.365, -2.036]} rotation={[1.595, -0.003, 0.008]} scale={[1.006, 1.165, 1.006]}>
          <mesh name="Glass" geometry={nodes.Glass.geometry} material={materials['Glass.006']} position={[0, -0.085, -0.612]} />
        </group>
        <group name="2_panel_sliding_window001" position={[0.069, 0.999, -2.056]} scale={[1.45, 1.45, 1.679]} />
        <group name="2_panel_sliding_window002" position={[0.069, 0.999, -2.056]} scale={[1.45, 1.45, 1.679]}>
          <group name="Cube002">
            <mesh name="Cube136" geometry={nodes.Cube136.geometry} material={materials['glass.003']} />
            <mesh name="Cube136_1" geometry={nodes.Cube136_1.geometry} material={materials['White Vinyl.003']} />
            <mesh name="Cube136_2" geometry={nodes.Cube136_2.geometry} material={materials['black rubber.003']} />
          </group>
          <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['glass.003']}>
            <group name="Cube001" position={[0.485, 0, 0]}>
              <mesh name="Cube138" geometry={nodes.Cube138.geometry} material={materials['Material.072']} />
              <mesh name="Cube138_1" geometry={nodes.Cube138_1.geometry} material={materials['black rubber.003']} />
            </group>
          </mesh>
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['White Vinyl.003']}>
            <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['black rubber.003']} position={[-0.053, -0.89, 1.21]} scale={1.259} />
          </mesh>
        </group>
        <group name="Curtain">
          <mesh name="curtain001" geometry={nodes.curtain001.geometry} material={materials['Material.073']} position={[0.078, 0.693, -1.949]} scale={[0.245, 0.794, 1]} />
          <mesh name="curtain_hook006" geometry={nodes.curtain_hook006.geometry} material={materials['plast_bily.002']} position={[0.078, 0.693, -1.949]} scale={[0.717, 0.794, 1]} />
          <mesh name="garnyz" geometry={nodes.garnyz.geometry} material={materials['wood_light_brown.002']} position={[0.078, 0.693, -1.949]} scale={[0.717, 0.794, 1]} />
          <mesh name="Torus" geometry={nodes.Torus.geometry} material={materials['wood_light_brown.002']} position={[0.078, 0.693, -1.949]} scale={[0.717, 0.794, 1]} />
        </group>
        <pointLight name="Point" intensity={6} decay={2.5} distance={20} color="#fff9d1" position={[-0.008, 2.985, 0.008]} rotation={[-Math.PI / 2, 0, 0]} />
        <pointLight name="Point001" intensity={6} decay={2.5} distance={20} color="#fff9d1" position={[-0.008, 2.039, 0.008]} rotation={[-Math.PI / 2, 0, 0]} />
        <pointLight name="Point002" intensity={3} decay={2.5} distance={20} color="#fff9d1" position={[2.679, 1.967, -0.417]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Wooden Floor.003']} position={[-0.007, 0.004, -0.024]} scale={[1.825, 0.637, 2.113]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.049']} position={[-0.007, -0.003, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="bookshelf002" geometry={nodes.bookshelf002.geometry} material={materials['Material.050']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="bookshelf" geometry={nodes.bookshelf.geometry} material={materials['Wood.007']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0001_Layer-3004" geometry={nodes['books-3981515_0001_Layer-3004'].geometry} material={materials['books-3981515_0001_Layer-3.003']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0001_Layer-3003" geometry={nodes['books-3981515_0001_Layer-3003'].geometry} material={materials['books-3981515_0001_Layer-3.003']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0001_Layer-3002" geometry={nodes['books-3981515_0001_Layer-3002'].geometry} material={materials['books-3981515_0001_Layer-3.003']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0001_Layer-3" geometry={nodes['books-3981515_0001_Layer-3'].geometry} material={materials['books-3981515_0001_Layer-3.003']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0000_Layer-2005" geometry={nodes['books-3981515_0000_Layer-2005'].geometry} material={materials['books-3981515_0000_Layer-2.003']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0000_Layer-2004" geometry={nodes['books-3981515_0000_Layer-2004'].geometry} material={materials['books-3981515_0000_Layer-2.003']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0000_Layer-2003" geometry={nodes['books-3981515_0000_Layer-2003'].geometry} material={materials['books-3981515_0000_Layer-2.003']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="books-3981515_0000_Layer-2002" geometry={nodes['books-3981515_0000_Layer-2002'].geometry} material={materials['books-3981515_0000_Layer-2.003']} position={[-0.007, -0.291, -0.024]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="polstar_2" geometry={nodes.polstar_2.geometry} material={materials['Material.057']} position={[-0.01, -0.447, 0.078]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="polstar_2001" geometry={nodes.polstar_2001.geometry} material={materials['Material.058']} position={[-0.005, -0.433, 0.05]} scale={[1.825, 1.825, 2.113]} />
        <mesh name="Beige_Carpet001" geometry={nodes.Beige_Carpet001.geometry} material={materials['Material.060']} position={[0.013, -0.286, -0.068]} scale={[1.825, 1.825, 2.113]} />
        <group name="Office_Chair_REX" position={[-0.027, 0.099, 0.421]} rotation={[0, 0.862, 0]} scale={[1.125, 1.029, 1.101]}>
          <mesh name="Plane026" geometry={nodes.Plane026.geometry} material={materials['Office Chair_Fabric.003']} />
          <mesh name="Plane026_1" geometry={nodes.Plane026_1.geometry} material={materials['Office Chair_Metal.003']} />
          <mesh name="Plane026_2" geometry={nodes.Plane026_2.geometry} material={materials['Office Chair_Painted Metal.003']} />
          <mesh name="Plane026_3" geometry={nodes.Plane026_3.geometry} material={materials['Office Chair_Plastic.003']} />
        </group>
        <mesh name="Lenovo_laptop" geometry={nodes.Lenovo_laptop.geometry} material={materials['prop_laptop_lenovo_body.003']} position={[0.79, 0.949, -0.045]} rotation={[0, -0.876, 0]} scale={0.001} />
        <group name="Autumn_Picture" position={[-1.809, 1.973, -0.004]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1.032, -0.891, -0.891]}>
          <mesh name="Plane027" geometry={nodes.Plane027.geometry} material={materials['Picture_1.003']} />
          <mesh name="Plane027_1" geometry={nodes.Plane027_1.geometry} material={materials['Frame_Black.003']} />
        </group>
                <mesh
          geometry={nodes.About_Hitbox.geometry}
          material={nodes.About_Hitbox.material}
          visible={false}
          position={[-1.737, 1.952, 0.013]}
          scale={[0.073, 0.438, 0.613]}
          onPointerOver={() => {
            onHover("About_Hitbox", true)
            document.body.style.cursor = "pointer"
          }}
          onPointerOut={() => {
            onHover("About_Hitbox", false)
            document.body.style.cursor = "auto"
          }}
          onClick={() => {
            // openPanel("About_Hitbox")
            navigate("/about")
          }}
        />
        <mesh
          ref={aboutAnimRef}
          geometry={nodes.About_Hitbox_Anim.geometry}
          material={whiteMaterial}
          position={[-1.664, 2.39, 0.626]}
          scale={[0.009, 0.009, 0.011]}
        />
        <mesh
          geometry={nodes.Dev_Work_Hitbox.geometry}
          material={nodes.Dev_Work_Hitbox.material}
          visible={false}
          position={[0.391, 0.82, 0.497]}
          scale={[0.748, 0.693, 0.951]}
          onPointerOver={() => {
            onHover("Dev_Work_Hitbox", true)
            document.body.style.cursor = "pointer"
          }}
          onPointerOut={() => {
            onHover("Dev_Work_Hitbox", false)
            document.body.style.cursor = "auto"
          }}
          onClick={() => {
            // openPanel("Dev_Work_Hitbox")
            navigate("/dev-work")
          }}
        />
        <mesh
          ref={devWorkAnimRef}
          geometry={nodes.Dev_Work_Hitbox_Anim.geometry}
          material={whiteMaterial}
          position={[1.126, 1.5, 1.432]}
          scale={[0.018, 0.018, 0.021]}
        />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.071']} position={[-0.599, 0.08, 0]} rotation={[-Math.PI, 0, 0]} scale={[2.5, 7.85, 2.5]} />
        {/* <mesh name="Dev_Work_Hitbox" geometry={nodes.Dev_Work_Hitbox.geometry} material={nodes.Dev_Work_Hitbox.material} position={[0.391, 0.82, 0.497]} scale={[0.748, 0.693, 0.951]} />
        <mesh name="Dev_Work_Hitbox_Anim" geometry={nodes.Dev_Work_Hitbox_Anim.geometry} material={nodes.Dev_Work_Hitbox_Anim.material} position={[1.126, 1.5, 1.432]} scale={[0.018, 0.018, 0.021]} />
        <mesh name="About_Hitbox" geometry={nodes.About_Hitbox.geometry} material={nodes.About_Hitbox.material} position={[-1.737, 1.952, 0.013]} scale={[0.073, 0.438, 0.613]} />
        <mesh name="About_Hitbox_Anim" geometry={nodes.About_Hitbox_Anim.geometry} material={nodes.About_Hitbox_Anim.material} position={[-1.664, 2.39, 0.626]} scale={[0.009, 0.009, 0.011]} /> */}
      </group>
    </group>
  )
}

useGLTF.preload('/models/HomeOffice2_v4.glb')
