/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HomeOffice3_v1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { gsap } from 'gsap'
import { useNavigate } from 'react-router'

export default function Model(props) {
  let navigate = useNavigate()


  const { nodes, materials } = useGLTF('/models/HomeOffice3_v1.glb')

  const whiteMaterial = new THREE.MeshBasicMaterial({ color: 0xffffff})

  const about2AnimRef = useRef()
  const devWork2AnimRef = useRef()

  const animationPairs = {
    About_2_Hitbox: { ref: about2AnimRef },
    Dev_Work_2_Hitbox: { ref: devWork2AnimRef },
    
  }
  const originalScales = {
    About_2_Hitbox: { x: 0.01, y: 0.01, z: 0.01 },
    Dev_Work_2_Hitbox: { x: 0.008, y: 0.008, z: 0.01 }
  };
  // Handle Hover
  const onHover = (key, isHovering) => {
    const animObject = animationPairs[key]
  // Như này to quá
  //   gsap.to(animObject.ref.current.scale, {
  //     x: isHovering ? 1 : 0,
  //     y: isHovering ? 1 : 0,
  //     z: isHovering ? 1 : 0, 
  //     duration: 0.8,
  // })
    const base = originalScales[key];
    gsap.to(animObject.ref.current.scale, {
      x: isHovering ? base.x : 0,
      y: isHovering ? base.y : 0,
      z: isHovering ? base.z : 0,
      duration: 0.8,
    });
  }
  return (
    <group {...props} dispose={null}>
      <group position={[-1.868, 0.322, -29.793]} rotation={[0, 1.558, 0]} scale={[1.327, 1.137, 1.158]}>
        <mesh geometry={nodes.cabinet.geometry} material={materials['Walnut Wood.003']} position={[0, -0.012, 0.196]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.957}>
          <mesh geometry={nodes.backboard.geometry} material={materials['Procedural Wood.003']} position={[0, -0.04, 0.203]} />
          <mesh geometry={nodes.backboard001.geometry} material={materials['Procedural Wood.003']} position={[-1.3, 0.71, 0.203]} />
          <mesh geometry={nodes.leg_1.geometry} material={materials['Stainless Steel.003']} position={[0.929, -0.195, -0.154]} />
          <mesh geometry={nodes.leg_2.geometry} material={materials['Stainless Steel.003']} position={[0, -0.195, -0.154]} />
          <mesh geometry={nodes.leg_3.geometry} material={materials['Stainless Steel.003']} position={[-0.929, -0.195, 0.154]} />
          <mesh geometry={nodes.leg_3001.geometry} material={materials['Stainless Steel.003']} position={[-1.071, -0.195, 0.154]} />
          <mesh geometry={nodes.leg_3002.geometry} material={materials['Stainless Steel.003']} position={[-1.529, -0.195, 0.154]} />
          <mesh geometry={nodes.leg_4.geometry} material={materials['Stainless Steel.003']} position={[0, -0.195, 0.154]} />
          <mesh geometry={nodes.leg_5.geometry} material={materials['Stainless Steel.003']} position={[-0.929, -0.195, -0.154]} />
          <mesh geometry={nodes.leg_5001.geometry} material={materials['Stainless Steel.003']} position={[-1.071, -0.195, -0.154]} />
          <mesh geometry={nodes.leg_5002.geometry} material={materials['Stainless Steel.003']} position={[-1.529, -0.195, -0.154]} />
          <mesh geometry={nodes.leg_6.geometry} material={materials['Stainless Steel.003']} position={[0.929, -0.195, 0.154]} />
          <mesh geometry={nodes.separator_1.geometry} material={materials['Procedural Wood.003']} position={[-0.495, -0.089, 0]} />
          <mesh geometry={nodes.separator_2.geometry} material={materials['Procedural Wood.003']} position={[0, -0.089, 0]} />
          <mesh geometry={nodes.separator_3.geometry} material={materials['Procedural Wood.003']} position={[0.495, -0.089, 0]} />
          <mesh geometry={nodes.side_desk_l.geometry} material={materials['Furniture Wood.003']} position={[0.99, -0.04, 0]} />
          <mesh geometry={nodes.side_desk_l001.geometry} material={materials['Furniture Wood.003']} position={[-0.99, -0.04, 0]} />
          <mesh geometry={nodes.side_desk_l002.geometry} material={materials['Furniture Wood.003']} position={[-1.013, 0.71, 0]} />
          <mesh geometry={nodes.side_desk_l003.geometry} material={materials['Furniture Wood.003']} position={[-1.3, 0.71, 0]} />
          <mesh geometry={nodes.side_desk_l004.geometry} material={materials['Furniture Wood.003']} position={[-1.59, 0.71, 0]} />
          <mesh geometry={nodes.support.geometry} material={materials['Cross Brushed Metal.003']} position={[0.972, -0.015, -0.16]} />
          <mesh geometry={nodes.support001.geometry} material={materials['Cross Brushed Metal.003']} position={[0.972, -0.015, 0.16]} />
          <mesh geometry={nodes.support002.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.972, -0.015, -0.16]} scale={-1} />
          <mesh geometry={nodes.support003.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.972, -0.015, 0.16]} scale={-1} />
          <mesh geometry={nodes.support004.geometry} material={materials['Cross Brushed Metal.003']} position={[-1.028, 0.082, -0.16]}>
            <mesh geometry={nodes.support005.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.255, 0, 0]} rotation={[Math.PI, 0, Math.PI]} />
            <mesh geometry={nodes.support006.geometry} material={materials['Cross Brushed Metal.003']} position={[0, 0, 0.32]} />
            <mesh geometry={nodes.support007.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.255, 0, 0.32]} rotation={[Math.PI, 0, Math.PI]} />
          </mesh>
          <mesh geometry={nodes.support008.geometry} material={materials['Cross Brushed Metal.003']} position={[-1.028, 0.682, -0.16]}>
            <mesh geometry={nodes.support009.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.255, 0, 0]} rotation={[Math.PI, 0, Math.PI]} />
            <mesh geometry={nodes.support010.geometry} material={materials['Cross Brushed Metal.003']} position={[0, 0, 0.32]} />
            <mesh geometry={nodes.support011.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.255, 0, 0.32]} rotation={[Math.PI, 0, Math.PI]} />
          </mesh>
          <mesh geometry={nodes.support012.geometry} material={materials['Cross Brushed Metal.003']} position={[-1.028, 0.382, -0.16]}>
            <mesh geometry={nodes.support013.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.255, 0, 0]} rotation={[Math.PI, 0, Math.PI]} />
            <mesh geometry={nodes.support014.geometry} material={materials['Cross Brushed Metal.003']} position={[0, 0, 0.32]} />
            <mesh geometry={nodes.support015.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.255, 0, 0.32]} rotation={[Math.PI, 0, Math.PI]} />
          </mesh>
          <mesh geometry={nodes.support016.geometry} material={materials['Cross Brushed Metal.003']} position={[-1.028, 0.983, -0.16]}>
            <mesh geometry={nodes.support017.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.255, 0, 0]} rotation={[Math.PI, 0, Math.PI]} />
            <mesh geometry={nodes.support018.geometry} material={materials['Cross Brushed Metal.003']} position={[0, 0, 0.32]} />
            <mesh geometry={nodes.support019.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.255, 0, 0.32]} rotation={[Math.PI, 0, Math.PI]} />
          </mesh>
          <mesh geometry={nodes.support020.geometry} material={materials['Cross Brushed Metal.003']} position={[-1.028, 1.283, -0.16]}>
            <mesh geometry={nodes.support021.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.255, 0, 0]} rotation={[Math.PI, 0, Math.PI]} />
            <mesh geometry={nodes.support022.geometry} material={materials['Cross Brushed Metal.003']} position={[0, 0, 0.32]} />
            <mesh geometry={nodes.support023.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.255, 0, 0.32]} rotation={[Math.PI, 0, Math.PI]} />
          </mesh>
          <mesh geometry={nodes.support024.geometry} material={materials['Cross Brushed Metal.003']} position={[-1.028, 1.583, -0.16]}>
            <mesh geometry={nodes.support025.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.545, 0, 0]} rotation={[Math.PI, 0, Math.PI]} />
            <mesh geometry={nodes.support026.geometry} material={materials['Cross Brushed Metal.003']} position={[0, 0, 0.32]} />
            <mesh geometry={nodes.support027.geometry} material={materials['Cross Brushed Metal.003']} position={[-0.545, 0, 0.32]} rotation={[Math.PI, 0, Math.PI]} />
          </mesh>
          <mesh geometry={nodes.top_desk.geometry} material={materials['Walnut Wood.003']} position={[0, 0.1, 0]} />
          <mesh geometry={nodes.top_desk001.geometry} material={materials['Walnut Wood.003']} position={[0, -0.18, 0]} />
          <mesh geometry={nodes.top_desk002.geometry} material={materials['Walnut Wood.003']} position={[-1.3, 1.6, 0]} />
          <mesh geometry={nodes.top_desk003.geometry} material={materials['Walnut Wood.003']} position={[-1.3, -0.18, 0]} />
          <mesh geometry={nodes.top_desk004.geometry} material={materials['Walnut Wood.003']} position={[-1.155, 0.1, 0]} />
          <mesh geometry={nodes.top_desk005.geometry} material={materials['Walnut Wood.003']} position={[-1.155, 0.4, 0]} />
          <mesh geometry={nodes.top_desk006.geometry} material={materials['Walnut Wood.003']} position={[-1.155, 0.7, 0]} />
          <mesh geometry={nodes.top_desk007.geometry} material={materials['Walnut Wood.003']} position={[-1.155, 1, 0]} />
          <mesh geometry={nodes.top_desk008.geometry} material={materials['Walnut Wood.003']} position={[-1.155, 1.3, 0]} />
        </mesh>
      </group>
      <group position={[-1.86, 2.068, -29.828]} rotation={[0, 0, -1.583]} scale={[0.874, 0.89, 1.02]}>
        <mesh geometry={nodes.bronze.geometry} material={materials['Mat-Bronze']} />
        <mesh geometry={nodes.glass.geometry} material={materials['Mat-Glass']} />
        <mesh geometry={nodes.gold.geometry} material={materials['Mat-Gold']} />
        <mesh geometry={nodes.metal.geometry} material={materials['Mat-metal']} />
        <mesh geometry={nodes.paint.geometry} material={materials['Mat-Paint']} />
        <mesh geometry={nodes.paint_metal.geometry} material={materials['Mat-Paint_metal']} position={[0, 0.019, 0.047]} scale={1.221} />
        <mesh geometry={nodes.plastic.geometry} material={materials['Mat-Plastic']} />
        <mesh geometry={nodes.white.geometry} material={materials['Mat-White']} />
        <mesh geometry={nodes.wood.geometry} material={materials['Mat-Wood']} />
      </group>
      <group position={[-1.568, 0.318, -28.277]} scale={[1.226, 1.204, 1.405]}>
        <mesh geometry={nodes.ground002.geometry} material={materials['TT_checker_1024x1024_UV_GRID.001']} position={[0, -0.192, 0]} />
        <mesh geometry={nodes.plant002.geometry} material={materials.leave_1_MatSG} position={[0, -0.192, 0]} />
        <mesh geometry={nodes.pot002.geometry} material={materials['TT_checker_1024x1024_UV_GRID.002']} position={[0, -0.192, 0]} />
      </group>
      <group position={[-1.581, 0.446, -28.779]} rotation={[-Math.PI, 1.525, -Math.PI]} scale={[0.487, 0.417, 0.425]}>
        <group position={[0, 0.305, 0]} rotation={[0, 1.571, 0]} scale={1.979}>
          <mesh geometry={nodes.Cube281.geometry} material={materials.rubber} />
          <mesh geometry={nodes.Cube281_1.geometry} material={materials.mainspeakercolor} />
          <mesh geometry={nodes.Cube281_2.geometry} material={materials.DriverBlack} />
          <mesh geometry={nodes.Cube281_3.geometry} material={materials.tweetercolor} />
          <mesh geometry={nodes.Cube281_4.geometry} material={materials.tweeterknob} />
          <mesh geometry={nodes.Cube281_5.geometry} material={materials.Redglos} />
          <mesh geometry={nodes.Cube281_6.geometry} material={materials.blackgloss} />
          <mesh geometry={nodes.Cube281_7.geometry} material={materials.DriverWhite} />
          <mesh geometry={nodes.Cube281_8.geometry} material={materials['metal.001']} />
          <group position={[0.149, 0.014, 0]} rotation={[0, -1.571, 0]} scale={[1, 1, 0.338]}>
            <mesh geometry={nodes.Plane013.geometry} material={materials.DriverBlack} />
            <mesh geometry={nodes.Plane013_1.geometry} material={materials['metal.001']} />
            <mesh geometry={nodes.Plane013_2.geometry} material={materials.Fabric} />
          </group>
        </group>
      </group>
      <group position={[0.221, 0.323, -29.845]} scale={[1.011, 1.686, 1.968]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials.carpet} position={[0.052, -0.128, 0]} />
      </group>
      <group position={[0.276, 0.334, -29.733]} rotation={[0, -1.557, 0]} scale={[1.25, 1.071, 1.09]}>
        <mesh geometry={nodes.bottom_shelf.geometry} material={materials.wooden} position={[0, 0, -0.31]} />
        <mesh geometry={nodes.main_desk.geometry} material={materials.wooden} position={[-0.133, -0.216, -0.312]} scale={[1.2, 1, 1]} />
        <mesh geometry={nodes.main_leg.geometry} material={materials['metal.002']} position={[-0.25, -0.216, -0.31]} />
        <mesh geometry={nodes.second_desk.geometry} material={materials.wooden} position={[0, -0.216, -0.31]} />
        <mesh geometry={nodes.second_desk001.geometry} material={materials['metal.002']} position={[0, -0.216, -0.31]} />
        <mesh geometry={nodes.shelf_border_Desk_bottom.geometry} material={materials.wooden} position={[0, -0.246, -0.31]} scale={[1, 1.13, 1]} />
        <mesh geometry={nodes.shelf_border_desk_upper.geometry} material={materials.wooden} position={[0, -0.216, -0.31]} />
        <mesh geometry={nodes.shelfs_legs1.geometry} material={materials['metal.002']} position={[0, 0, -0.31]} />
        <mesh geometry={nodes.shelfs_legs2.geometry} material={materials['metal.002']} position={[0, -0.216, -0.31]} />
        <mesh geometry={nodes.upper_shelf.geometry} material={materials.wooden} position={[0, -0.216, -0.31]} />
      </group>
      <group position={[-0.047, 0.32, -30.074]} scale={[0.757, 0.743, 0.868]}>
        <group position={[0, -0.297, -0.07]} rotation={[0, 1.304, 0]} scale={1.363}>
          <mesh geometry={nodes.Plane002_1.geometry} material={materials['Office Chair_Fabric']} />
          <mesh geometry={nodes.Plane002_2.geometry} material={materials['Office Chair_Metal']} />
          <mesh geometry={nodes.Plane002_3.geometry} material={materials['Office Chair_Painted Metal']} />
          <mesh geometry={nodes.Plane002_4.geometry} material={materials['Office Chair_Plastic']} />
        </group>
      </group>
      <group position={[0.107, 0.914, -29.175]} rotation={[0, 0.235, 0]} scale={[1.156, 1.115, 1.306]}>
        <group position={[-0.021, 0.098, 0.007]} rotation={[0.03, 0.004, 0.02]}>
          <mesh geometry={nodes.Cube303.geometry} material={materials['book cover']} />
          <mesh geometry={nodes.Cube303_1.geometry} material={materials['stacked paper']} />
        </group>
        <group position={[-0.001, 0.034, -0.007]} rotation={[0.024, 0.297, 0.015]}>
          <mesh geometry={nodes.Cube302.geometry} material={materials['book cover']} />
          <mesh geometry={nodes.Cube302_1.geometry} material={materials['stacked paper']} />
        </group>
        <group position={[0.013, 0.009, -0.013]} rotation={[0.008, 0.059, 0.003]}>
          <mesh geometry={nodes.Cube301.geometry} material={materials['book cover.001']} />
          <mesh geometry={nodes.Cube301_1.geometry} material={materials['stacked paper.001']} />
        </group>
        <group position={[-0.015, 0.077, 0.002]} rotation={[0.026, 0.24, 0.022]}>
          <mesh geometry={nodes.Cube300.geometry} material={materials['book cover']} />
          <mesh geometry={nodes.Cube300_1.geometry} material={materials['stacked paper']} />
        </group>
        <group position={[0.017, 0, -0.017]} rotation={[0.007, 0.144, 0.03]}>
          <mesh geometry={nodes.Cube299.geometry} material={materials['book cover']} />
          <mesh geometry={nodes.Cube299_1.geometry} material={materials['stacked paper']} />
        </group>
        <group position={[-0.011, 0.055, 0]} rotation={[0.029, 0.094, 0.018]}>
          <mesh geometry={nodes.Cube298.geometry} material={materials['book cover']} />
          <mesh geometry={nodes.Cube298_1.geometry} material={materials['stacked paper']} />
        </group>
        <group position={[0.008, 0.022, -0.028]} rotation={[0.023, -0.076, 0.01]}>
          <mesh geometry={nodes.Cube297.geometry} material={materials['book cover']} />
          <mesh geometry={nodes.Cube297_1.geometry} material={materials['stacked paper']} />
        </group>
      </group>
      <group position={[0.851, 0.501, -29.178]} scale={[0.968, 0.95, 1.109]}>
        <group position={[-0.044, 0.12, 0.006]} rotation={[1.573, -0.183, -1.563]} scale={1.045}>
          <mesh geometry={nodes.Cube305.geometry} material={materials['book cover.002']} />
          <mesh geometry={nodes.Cube305_1.geometry} material={materials['stacked paper.002']} />
        </group>
        <group position={[-0.026, 0.122, 0.005]} rotation={[1.572, -0.181, -1.562]} scale={1.045}>
          <mesh geometry={nodes.Cube304.geometry} material={materials['book cover.002']} />
          <mesh geometry={nodes.Cube304_1.geometry} material={materials['stacked paper.002']} />
        </group>
        <group position={[-0.066, 0.123, 0.007]} rotation={[1.572, -0.184, -1.563]} scale={1.045}>
          <mesh geometry={nodes.Cube307.geometry} material={materials['book cover.002']} />
          <mesh geometry={nodes.Cube307_1.geometry} material={materials['stacked paper.002']} />
        </group>
        <group position={[-0.177, 0.115, 0.009]} rotation={[1.565, -0.343, -1.566]} scale={1.045}>
          <mesh geometry={nodes.Cube308.geometry} material={materials['book cover.003']} />
          <mesh geometry={nodes.Cube308_1.geometry} material={materials['stacked paper.003']} />
        </group>
        <group position={[-0.157, 0.12, 0.003]} rotation={[1.574, -0.339, -1.563]} scale={1.045}>
          <mesh geometry={nodes.Cube005.geometry} material={materials['book cover.002']} />
          <mesh geometry={nodes.Cube005_1.geometry} material={materials['stacked paper.002']} />
        </group>
        <group position={[-0.105, 0.102, -0.001]} rotation={[1.575, -0.323, -1.563]} scale={1.045}>
          <mesh geometry={nodes.Cube306.geometry} material={materials['book cover.002']} />
          <mesh geometry={nodes.Cube306_1.geometry} material={materials['stacked paper.002']} />
        </group>
        <group position={[-0.116, 0.118, 0.003]} rotation={[1.571, -0.337, -1.564]} scale={1.045}>
          <mesh geometry={nodes.Cube006_1.geometry} material={materials['book cover.002']} />
          <mesh geometry={nodes.Cube006_2.geometry} material={materials['stacked paper.002']} />
        </group>
        <group position={[-0.134, 0.117, 0.008]} rotation={[1.573, -0.338, -1.564]} scale={1.045}>
          <mesh geometry={nodes.Cube007.geometry} material={materials['book cover.002']} />
          <mesh geometry={nodes.Cube007_1.geometry} material={materials['stacked paper.002']} />
        </group>
        <group position={[-0.204, 0.108, 0.011]} rotation={[1.573, -0.44, -1.564]}>
          <mesh geometry={nodes.Cube008.geometry} material={materials['book cover.002']} />
          <mesh geometry={nodes.Cube008_1.geometry} material={materials['stacked paper.002']} />
        </group>
      </group>
      <group position={[-1.581, 0.446, -30.83]} rotation={[-Math.PI, 1.525, -Math.PI]} scale={[0.487, 0.417, 0.425]}>
        <group position={[0.046, 0.305, 0.002]} rotation={[0, 1.571, 0]} scale={1.979}>
          <mesh geometry={nodes.Cube009.geometry} material={materials['rubber.001']} />
          <mesh geometry={nodes.Cube009_1.geometry} material={materials['mainspeakercolor.001']} />
          <mesh geometry={nodes.Cube009_2.geometry} material={materials['DriverBlack.001']} />
          <mesh geometry={nodes.Cube009_3.geometry} material={materials['tweetercolor.001']} />
          <mesh geometry={nodes.Cube009_4.geometry} material={materials['tweeterknob.001']} />
          <mesh geometry={nodes.Cube009_5.geometry} material={materials['Redglos.001']} />
          <mesh geometry={nodes.Cube009_6.geometry} material={materials['blackgloss.001']} />
          <mesh geometry={nodes.Cube009_7.geometry} material={materials['DriverWhite.001']} />
          <mesh geometry={nodes.Cube009_8.geometry} material={materials['metal.004']} />
        </group>
      </group>
      <group position={[-1.656, 1.771, -31.637]} rotation={[1.58, 0.011, -1.493]} scale={[2.042, 1.784, 1.748]}>
        <group position={[-0.101, -0.641, -0.011]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Mesh017.geometry} material={materials['Wood.001']} />
          <mesh geometry={nodes.Mesh017_1.geometry} material={materials['Material.001']} />
        </group>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Vidro.001']} position={[-0.101, -0.641, -0.001]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-1.114, 1.159, -30.993]} rotation={[0, 0.235, 0]} scale={[1.156, 1.115, 1.306]}>
        <group position={[-0.269, 0.635, -0.325]} rotation={[1.752, 0, Math.PI]} scale={[1.1, 1.3, 1.01]}>
          <mesh geometry={nodes.Cube014.geometry} material={materials['book cover.007']} />
          <mesh geometry={nodes.Cube014_1.geometry} material={materials['stacked paper.007']} />
        </group>
      </group>
      <group position={[-1.245, 2.193, -30.94]} rotation={[0, 0.235, 0]} scale={[1.156, 1.115, 1.306]}>
        <group position={[-0.175, -0.861, -0.305]} rotation={[1.371, 0, -Math.PI]} scale={[1.2, 1.5, 1.2]}>
          <mesh geometry={nodes.Cube015.geometry} material={materials['book cover.008']} />
          <mesh geometry={nodes.Cube015_1.geometry} material={materials['stacked paper.008']} />
        </group>
      </group>
      <group position={[-1.245, 2.193, -30.876]} rotation={[0, 0.235, 0]} scale={[1.156, 1.115, 1.306]}>
        <group position={[-0.175, -0.881, -0.306]} rotation={[1.371, 0, -Math.PI]}>
          <mesh geometry={nodes.Cube016.geometry} material={materials['book cover.009']} />
          <mesh geometry={nodes.Cube016_1.geometry} material={materials['stacked paper.009']} />
        </group>
      </group>
      <group position={[-1.245, 2.869, -30.876]} rotation={[0, 0.235, 0]} scale={[1.156, 1.115, 1.306]}>
        <group position={[-0.181, -0.911, -0.304]} rotation={[1.752, 0, -Math.PI]}>
          <mesh geometry={nodes.Cube017.geometry} material={materials['book cover.010']} />
          <mesh geometry={nodes.Cube017_1.geometry} material={materials['stacked paper.010']} />
        </group>
      </group>
      <group position={[-1.114, 1.147, -30.993]} rotation={[0, 0.235, 0]} scale={[1.156, 1.115, 1.306]}>
        <group position={[-0.29, 0.072, -0.343]} rotation={[1.371, 0, -Math.PI]} scale={[1.1, 1, 1.15]}>
          <mesh geometry={nodes.Cube019_1.geometry} material={materials['book cover.012']} />
          <mesh geometry={nodes.Cube019_2.geometry} material={materials['stacked paper.012']} />
        </group>
      </group>
      <group position={[-1.114, 1.159, -30.993]} rotation={[0, 0.235, 0]} scale={[1.156, 1.115, 1.306]}>
        <group position={[-0.28, 0.635, -0.286]} rotation={[1.752, 0, Math.PI]} scale={[1.1, 1, 1.1]}>
          <mesh geometry={nodes.Cube020_1.geometry} material={materials['book cover.013']} />
          <mesh geometry={nodes.Cube020_2.geometry} material={materials['stacked paper.013']} />
        </group>
      </group>
      <group position={[0.427, 1.447, -30.65]} rotation={[1.58, 0.011, -1.493]} scale={[2.042, 1.784, 1.748]}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Vidro colorido.001']} position={[0.001, 0.096, 0.278]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-1.044, 0.934, -31.079]} rotation={[1.58, 0.011, -1.493]} scale={[2.042, 1.784, 1.748]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials['Material.004']} position={[-0.14, 0.944, -0.058]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-1.044, 0.934, -31.188]} rotation={[1.58, 0.011, -1.493]} scale={[2.042, 1.784, 1.748]}>
        <mesh geometry={nodes.Cube042.geometry} material={materials['Ceramica off white.001']} position={[0.012, -0.324, 0.075]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.551, 0.934, -31.079]} rotation={[1.58, 0.011, -1.493]} scale={[2.042, 1.784, 1.748]}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.005']} position={[0.13, 0.525, 0.036]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-1.868, 0.322, -29.793]} rotation={[0, 1.558, 0]} scale={[1.327, 1.137, 1.158]}>
        <mesh geometry={nodes.cabinet001.geometry} material={materials['Walnut Wood.001']} position={[0, -0.012, 0.196]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.957} />
      </group>
      <group position={[-1.868, 0.322, -29.793]} rotation={[0, 1.558, 0]} scale={[1.327, 1.137, 1.158]}>
        <mesh geometry={nodes.cabinet002.geometry} material={materials['Walnut Wood.002']} position={[0, -0.012, 0.196]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.957} />
      </group>
      <pointLight intensity={20} decay={2.5} distance={15} color="#99ccfc" position={[-0.072, 2.722, -29.858]} rotation={[-Math.PI / 2, 0, 0]} scale={[-13.627, -26.597, -51.732]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Wood Floor']} position={[-0.122, 0.083, -29.882]} scale={[1.78, 0.529, 2.041]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.002']} position={[-0.114, 1.735, -29.873]} scale={[1.78, 1.748, 2.041]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.006']} position={[0, -0.09, -29.74]} rotation={[-Math.PI, 0, 0]} scale={[18, 7.85, 18]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Frosted Glass.003']} position={[-1.405, 1.721, -31.622]} rotation={[Math.PI, -1.558, Math.PI]} scale={[1.27, 1.088, 1.108]} />
      <mesh geometry={nodes.drawer_L.geometry} material={materials['Black Plastic.003']} position={[-1.413, 0.212, -29.471]} rotation={[Math.PI, -1.558, Math.PI]} scale={[1.27, 1.088, 1.108]}>
        <mesh geometry={nodes.drawer_2.geometry} material={materials['Procedural Wood.003']} position={[0, -0.007, 0.183]} />
      </mesh>
      <mesh geometry={nodes.drawer_LL.geometry} material={materials['Black Plastic.003']} position={[-1.419, 0.212, -28.842]} rotation={[Math.PI, -1.558, Math.PI]} scale={[1.27, 1.088, 1.108]}>
        <mesh geometry={nodes.drawer_1.geometry} material={materials['Procedural Wood.003']} position={[0, -0.007, 0.183]} />
      </mesh>
      <mesh geometry={nodes.drawer_RR.geometry} material={materials['Black Plastic.003']} position={[-1.4, 0.212, -30.729]} rotation={[Math.PI, -1.558, Math.PI]} scale={[1.27, 1.088, 1.108]}>
        <mesh geometry={nodes.drawer_4.geometry} material={materials['Procedural Wood.003']} position={[0, -0.007, 0.183]} />
      </mesh>
      <group position={[-1.657, 0.415, -29.843]} rotation={[0, 1.561, 0]} scale={[1.575, 1.349, 1.373]}>
        <mesh geometry={nodes.Cube279.geometry} material={materials['grid plastic']} />
        <mesh geometry={nodes.Cube279_1.geometry} material={materials['darkish grey plastic']} />
        <mesh geometry={nodes.Cube279_2.geometry} material={materials.screen} />
        <mesh geometry={nodes['43_inch_remake001'].geometry} material={materials['darkish grey plastic']} position={[0, 0.345, -0.133]} />
        <group position={[0, 0.345, -0.132]}>
          <mesh geometry={nodes.Cube278.geometry} material={materials['darkish grey plastic']} />
          <mesh geometry={nodes.Cube278_1.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cube278_2.geometry} material={materials['plastic yelow']} />
          <mesh geometry={nodes.Cube278_3.geometry} material={materials['plastic red']} />
        </group>
      </group>
      <group position={[0.648, 0.928, -30.117]} rotation={[0, -1.308, 0]} scale={[1.204, 1.028, 1.07]}>
        <mesh geometry={nodes.Cube292.geometry} material={materials['metal body']} />
        <mesh geometry={nodes.Cube292_1.geometry} material={materials['screen.001']} />
        <mesh geometry={nodes.Cube292_2.geometry} material={materials['darkish grey plastic.001']} />
        <mesh geometry={nodes.Cube292_3.geometry} material={materials['on of button']} />
        <mesh geometry={nodes.keyboard.geometry} material={materials['Material.003']} position={[-0.016, 0.015, 0]} />
        <group position={[0.001, 0.136, -0.14]}>
          <mesh geometry={nodes.Cube291.geometry} material={materials['metal body']} />
          <mesh geometry={nodes.Cube291_1.geometry} material={materials['screen.001']} />
          <mesh geometry={nodes.Cube291_2.geometry} material={materials.camera} />
        </group>
        <group position={[0.003, -0.102, -0.003]}>
          <mesh geometry={nodes.Cube290.geometry} material={materials['darkish grey plastic.001']} />
          <mesh geometry={nodes.Cube290_1.geometry} material={materials['metal.003']} />
          <mesh geometry={nodes.Cube290_2.geometry} material={materials['plastic yelow.001']} />
          <mesh geometry={nodes.Cube290_3.geometry} material={materials['plastic red.001']} />
        </group>
      </group>
      <mesh geometry={nodes.Eggplant_Lamp.geometry} material={materials.green_paint} position={[0.654, 0.9, -29.466]} rotation={[0, -0.999, 0]} scale={[1.685, 1.442, 1.592]}>
        <mesh geometry={nodes.strand1.geometry} material={materials.green_paint}>
          <mesh geometry={nodes.bulb1.geometry} material={materials.Lamp} position={[-0.074, 0.227, 0.001]} />
          <mesh geometry={nodes.flowerb1.geometry} material={materials.green_paint} position={[-0.074, 0.227, 0.001]} />
          <mesh geometry={nodes.Leave0.geometry} material={materials.green_paint} position={[-0.018, 0.071, 0.001]} />
          <mesh geometry={nodes.Leave1.geometry} material={materials.green_paint} position={[0, 0.101, 0.002]} />
          <mesh geometry={nodes.Leave2.geometry} material={materials.green_paint} position={[0.08, 0.179, 0.005]} />
          <mesh geometry={nodes.Leave3.geometry} material={materials.green_paint} position={[-0.001, 0.304, 0.001]} />
          <mesh geometry={nodes.strand2.geometry} material={materials.green_paint} position={[0.024, 0.161, -0.024]}>
            <mesh geometry={nodes.bulb3.geometry} material={materials.Lamp} position={[-0.028, -0.017, -0.026]} />
            <mesh geometry={nodes.flowerb3.geometry} material={materials.green_paint} position={[-0.028, -0.017, -0.026]} />
          </mesh>
          <mesh geometry={nodes.strand3.geometry} material={materials.green_paint} position={[0.034, 0.233, 0]}>
            <mesh geometry={nodes.bulb2.geometry} material={materials.Lamp} position={[-0.031, -0.018, 0.065]} />
            <mesh geometry={nodes.flowerb2.geometry} material={materials.green_paint} position={[-0.031, -0.018, 0.065]} />
          </mesh>
        </mesh>
      </mesh>
      <group position={[-0.409, 1.02, -31.895]} scale={[0.931, 0.914, 1.067]}>
        <mesh geometry={nodes.Cube309.geometry} material={materials['1 bh6601_1_face_vidro_transparente.002']} />
        <mesh geometry={nodes.Cube309_1.geometry} material={materials['esquadria branca.001']} />
        <mesh geometry={nodes.Cube309_2.geometry} material={materials['Borracha preta.001']} />
        <mesh geometry={nodes.Cube309_3.geometry} material={materials['Plastico preto.001']} />
        <mesh geometry={nodes.Cube309_4.geometry} material={materials['Vermelho3425.001']} />
      </group>
      <mesh geometry={nodes['books-3981515_0001_Layer-3001'].geometry} material={materials['books-3981515_0001_Layer-3.001']} position={[-0.227, -0.621, -29.834]} scale={[1.638, 1.154, 1.653]} />
      <group position={[-1.585, 1.844, -31.151]} rotation={[1.752, 0, Math.PI]} scale={[1.976, 2.848, 1.222]}>
        <mesh geometry={nodes.Cube018.geometry} material={materials['book cover.011']} />
        <mesh geometry={nodes.Cube018_1.geometry} material={materials['stacked paper.011']} />
      </group>
      <mesh geometry={nodes.drawer_R.geometry} material={materials['Black Plastic.004']} position={[-1.406, 0.212, -30.103]} rotation={[Math.PI, -1.558, Math.PI]} scale={[1.27, 1.088, 1.108]}>
        <mesh geometry={nodes.drawer_4001.geometry} material={materials['Procedural Wood.001']} position={[0, -0.007, 0.183]} />
      </mesh>
      <mesh
        geometry={nodes.About_2_Hitbox.geometry}
        material={nodes.About_2_Hitbox.material}
        visible={false}
        position={[-1.797, 2.053, -29.83]}
        scale={[0.071, 0.297, 0.376]}
        onPointerOver={() => {
          onHover("About_2_Hitbox", true)
          document.body.style.cursor = "pointer"
        }}
        onPointerOut={() => {
          onHover("About_2_Hitbox", false)
          document.body.style.cursor = "auto"
        }}
        onClick={() => {
          // openPanel("About_2_Hitbox")
          navigate("/about-2")
        }}
         />
      <mesh
        ref={about2AnimRef}
        geometry={nodes.About_2_Hitbox_Anim.geometry}
        material={whiteMaterial}
        position={[-1.726, 2.35, -29.454]}
        scale={0.01}
         />
      <mesh
        geometry={nodes.Dev_Work_2_Hitbox.geometry}
        material={nodes.Dev_Work_2_Hitbox.material}
        position={[0.286, 0.818, -29.856]}
        visible={false}
        scale={[0.89, 0.699, 1.121]}
        onPointerOver={() => {
          onHover("Dev_Work_2_Hitbox", true)
          document.body.style.cursor = "pointer"
        }}
        onPointerOut={() => {
          onHover("Dev_Work_2_Hitbox", false)
          document.body.style.cursor = "auto"
        }}
        onClick={() => {
          // openPanel("Dev_Work_2_Hitbox")
          navigate("/dev-work-2")
        }}
         />
      <mesh
        ref={devWork2AnimRef}
        geometry={nodes.Dev_Work_2_Hitbox_Anim.geometry}
        material={whiteMaterial}
        position={[1.176, 1.518, -28.714]}
        scale={[0.009, 0.009, 0.011]}
        />
      {/* <mesh geometry={nodes.About_2_Hitbox.geometry} material={nodes.About_2_Hitbox.material} position={[-1.797, 2.053, -29.83]} scale={[0.071, 0.297, 0.376]} />
      <mesh geometry={nodes.About_2_Hitbox_Anim.geometry} material={nodes.About_2_Hitbox_Anim.material} position={[-1.726, 2.35, -29.454]} scale={0.01} />
      <mesh geometry={nodes.Dev_Work_2_Hitbox.geometry} material={nodes.Dev_Work_2_Hitbox.material} position={[0.286, 0.818, -29.856]} scale={[0.89, 0.699, 1.121]} />
      <mesh geometry={nodes.Dev_Work_2_Hitbox_Anim.geometry} material={nodes.Dev_Work_2_Hitbox_Anim.material} position={[1.176, 1.518, -28.714]} scale={[0.009, 0.009, 0.011]} /> */}
      <mesh geometry={nodes.Cube026.geometry} material={materials['Black Plastic.006']} position={[-1.395, 0.438, -31.623]} rotation={[1.567, -1.563, -1.567]} scale={[1.261, 1.101, 1.246]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials['Black Plastic.007']} position={[-1.395, 1.08, -31.626]} rotation={[1.567, -1.563, -1.567]} scale={[1.261, 1.101, 1.246]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials['Frosted Glass.004']} position={[-1.405, 1.083, -31.622]} rotation={[Math.PI, -1.558, Math.PI]} scale={[1.27, 1.088, 1.108]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Frosted Glass.005']} position={[-1.405, 0.434, -31.622]} rotation={[Math.PI, -1.558, Math.PI]} scale={[1.27, 1.088, 1.108]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials['Black Plastic.008']} position={[-1.395, 1.722, -31.63]} rotation={[1.567, -1.563, -1.567]} scale={[1.261, 1.101, 1.246]} />
    </group>
  )
}

useGLTF.preload('/models/HomeOffice3_v1.glb')
